"use client";
import { useState, type KeyboardEvent } from "react";

interface JoinProps {
  onJoin: (name: string) => Promise<void>;
}

export function Join({ onJoin }: JoinProps) {
  const [name, setName] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);

  async function handleJoin() {
    const trimmed = name.trim();
    if (!trimmed) return;
    setLoading(true);
    setError(false);
    try {
      await onJoin(trimmed);
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  }

  function handleKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") handleJoin();
  }

  return (
    <section>
      <div className="eyebrow">Leadership Session · Live</div>
      <h1 className="page-heading mt-1.5 mb-0.5">
        Spot the <span className="text-acid italic">Bot</span>
      </h1>
      <p className="text-muted mt-2 text-sm leading-[1.4]">
        Grab a table, pick a team name, and put your heads together. You&apos;ll get a stack of text
        samples — for each one, decide together: written by a <b className="text-human">human</b>,
        or generated by an <b className="text-bot">AI</b>? Most correct calls in <b>10 minutes</b>{" "}
        takes the trophy.
      </p>
      <div className="card">
        <label
          className="text-muted mb-2 block font-mono text-[11px] tracking-[2px] uppercase"
          htmlFor="name-input"
        >
          Team name
        </label>
        <input
          id="name-input"
          type="text"
          autoFocus
          maxLength={40}
          placeholder="e.g. Table 4 / The Smoke Ringers"
          autoComplete="off"
          value={name}
          onChange={(e) => setName(e.target.value)}
          onKeyDown={handleKeyDown}
          className="border-acid/20 text-ink focus:border-acid w-full rounded-xl border bg-[#0a0805] px-4 py-3.5 font-mono text-lg transition-shadow outline-none focus:shadow-[0_0_0_3px_rgba(255,106,26,0.12)]"
        />
        <button className="btn btn-primary" onClick={handleJoin} disabled={loading || !name.trim()}>
          {loading ? "Joining…" : "Enter as a team →"}
        </button>
        {error && (
          <p className="text-rust mt-3 text-center font-mono text-[12px]" role="alert">
            Couldn&apos;t join — check your connection and try again.
          </p>
        )}
        <p className="text-muted mt-4 text-center font-mono text-[11px] leading-[1.5]">
          One device per team. Pass it around and argue it out — that&apos;s the point.
        </p>
      </div>
    </section>
  );
}
