"use client";
import { useState, type KeyboardEvent } from "react";
import { randomTeamName } from "@/lib/team-names";

interface JoinProps {
  onJoin: (name: string) => Promise<void>;
}

export function Join({ onJoin }: JoinProps) {
  const [name, setName] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const [reserved, setReserved] = useState(false);

  async function handleJoin() {
    const trimmed = name.trim();
    if (trimmed.toLowerCase() === "host") {
      setReserved(true);
      return;
    }
    setReserved(false);
    // Blank is fine — give them a random BBQ name so nobody's blocked on naming.
    const finalName = trimmed || randomTeamName();
    setLoading(true);
    setError(false);
    try {
      await onJoin(finalName);
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  }

  function handleKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") handleJoin();
  }

  return (
    <section>
      <div className="eyebrow">Leadership Session · Live</div>
      <h1 className="page-heading mt-1.5 mb-0.5">
        Spot the <span className="text-acid italic">Bot</span>
      </h1>
      <p className="text-muted mt-2 text-sm leading-[1.4]">
        Grab a table, pick a team name, and put your heads together. You&apos;ll get a stack of text
        samples — for each one, decide together: written by a <b className="text-human">human</b>,
        or generated by an <b className="text-bot">AI</b>? Most correct calls in <b>10 minutes</b>{" "}
        takes the trophy.
      </p>
      <div className="card">
        <label
          className="text-muted mb-2 block font-mono text-[11px] tracking-[2px] uppercase"
          htmlFor="name-input"
        >
          Team name
        </label>
        <div className="flex gap-2">
          <input
            id="name-input"
            type="text"
            autoFocus
            maxLength={40}
            placeholder="Team name (or leave blank)"
            autoComplete="off"
            value={name}
            onChange={(e) => setName(e.target.value)}
            onKeyDown={handleKeyDown}
            className="border-acid/20 text-ink focus:border-acid min-w-0 flex-1 rounded-xl border bg-[#0a0805] px-4 py-3.5 font-mono text-lg transition-shadow outline-none focus:shadow-[0_0_0_3px_rgba(255,106,26,0.12)]"
          />
          <button
            type="button"
            onClick={() => {
              setReserved(false);
              setName(randomTeamName());
            }}
            aria-label="Generate a random team name"
            title="Random BBQ name"
            className="border-acid/20 text-acid hover:border-acid shrink-0 rounded-xl border bg-[#0a0805] px-4 font-mono text-[11px] tracking-[1px] uppercase transition-colors"
          >
            Random
          </button>
        </div>
        <button className="btn btn-primary" onClick={handleJoin} disabled={loading}>
          {loading ? "Joining…" : "Enter as a team →"}
        </button>
        {error && (
          <p className="text-rust mt-3 text-center font-mono text-[12px]" role="alert">
            Couldn&apos;t join — check your connection and try again.
          </p>
        )}
        {reserved && (
          <p className="text-rust mt-3 text-center font-mono text-[12px]" role="alert">
            &quot;host&quot; is reserved — pick a different team name.
          </p>
        )}
        <p className="text-muted mt-4 text-center font-mono text-[11px] leading-[1.5]">
          One device per team. Tap Random for a name (or leave it blank and we&apos;ll pick one).
          Pass it around and argue it out — that&apos;s the point.
        </p>
      </div>
    </section>
  );
}
