// AUTO-GENERATED by scripts/gen-avatars.mjs — do not edit by hand.
// Team-avatar icon set: pixel-art BBQ foods + veggies in public/avatars/.
// Client-safe (no server-only imports) so the browser, the join/avatar API
// routes, and the archive page can all share one source of truth.
import { hashStr } from "./game";

export const AVATARS: string[] = [
  "asparagus-spears.png",
  "avocado.png",
  "baby-back-ribs.png",
  "baked-potato.png",
  "bbq-burnt-ends.png",
  "bbq-chicken-wing.png",
  "bbq-sauce-bottle.png",
  "beef-rib.png",
  "bowl-of-baked-beans.png",
  "bratwurst-sausage.png",
  "broccoli.png",
  "brown-potato.png",
  "brussels-sprout.png",
  "buttermilk-biscuit.png",
  "butternut-squash.png",
  "button-mushroom.png",
  "cauliflower.png",
  "celery-stalk.png",
  "cheeseburger.png",
  "cherry-tomatoes.png",
  "chicken-drumstick.png",
  "coleslaw.png",
  "corn-dog.png",
  "corn-on-the-cob.png",
  "cornbread.png",
  "cucumber.png",
  "deviled-eggs.png",
  "dinner-roll.png",
  "ear-of-grilled-corn.png",
  "french-fries.png",
  "garlic-bread.png",
  "garlic-bulb.png",
  "green-artichoke.png",
  "green-beans.png",
  "green-bell-pepper.png",
  "green-cabbage.png",
  "green-lime.png",
  "green-onion-scallion.png",
  "green-pickle.png",
  "green-zucchini.png",
  "grilled-bbq-drumstick.png",
  "grilled-cheese-sandwich.png",
  "grilled-fish.png",
  "grilled-hamburger.png",
  "grilled-hot-dog-in-a-bun.png",
  "grilled-pineapple-ring.png",
  "grilled-pork-chop.png",
  "grilled-sausage-link.png",
  "grilled-shrimp-skewer.png",
  "grilled-steak.png",
  "habanero-pepper.png",
  "head-of-lettuce.png",
  "hot-sauce-bottle.png",
  "hush-puppies.png",
  "jalapeno-pepper.png",
  "jalapeno-poppers.png",
  "jar-of-pickles.png",
  "kale-leaf.png",
  "ketchup-bottle.png",
  "leek.png",
  "mac-and-cheese.png",
  "mashed-potatoes.png",
  "meatball.png",
  "nachos-with-cheese.png",
  "okra.png",
  "onion-rings.png",
  "orange-carrot.png",
  "orange-pumpkin.png",
  "peas-in-a-pod.png",
  "pepper-shaker.png",
  "pickle-spear.png",
  "pork-belly.png",
  "potato-salad.png",
  "potato-wedges.png",
  "pulled-pork-sandwich.png",
  "purple-beet.png",
  "purple-eggplant.png",
  "rack-of-bbq-ribs.png",
  "red-bell-pepper.png",
  "red-chili-pepper.png",
  "red-onion.png",
  "red-radish.png",
  "ribeye-steak.png",
  "ripe-red-tomato.png",
  "salt-shaker.png",
  "shish-kabob-skewer.png",
  "skewer-of-grilled-vegetables.png",
  "slider-mini-burger.png",
  "smoked-beef-brisket-slice.png",
  "smoked-salmon-fillet.png",
  "smoked-turkey-leg.png",
  "soft-pretzel.png",
  "spinach-leaf.png",
  "stick-of-butter.png",
  "strips-of-bacon.png",
  "sweet-potato.png",
  "t-bone-steak.png",
  "tri-tip-roast.png",
  "turnip.png",
  "watermelon-slice.png",
  "whole-roast-chicken.png",
  "yellow-lemon.png",
  "yellow-mustard-bottle.png",
  "yellow-onion.png",
];

const AVATAR_SET: ReadonlySet<string> = new Set(AVATARS);

/** Public path for an avatar file name (e.g. "corn.png" -> "/avatars/corn.png"). */
export function avatarSrc(name: string): string {
  return `/avatars/${name}`;
}

/** True only for a file name that exists in the manifest — validate before storing. */
export function isValidAvatar(name: unknown): name is string {
  return typeof name === "string" && AVATAR_SET.has(name);
}

/** A random avatar (server picks one at join time). */
export function randomAvatar(): string {
  return AVATARS[Math.floor(Math.random() * AVATARS.length)];
}

/** Deterministic fallback for a team id — a stable placeholder when no avatar
 * is stored yet (legacy records, or before the RTDB subscription lands). */
export function avatarForTeam(id: string): string {
  return AVATARS[hashStr(id) % AVATARS.length];
}
