import type { PublicQuestion } from "./types";

// PROMPTS ONLY — no answers. Safe to ship to the browser. Generated from
// lib/questions.server.ts by scripts/gen-public-questions.ts — do not edit by hand.
export const PUBLIC_QUESTIONS: PublicQuestion[] = [
  { id: "bbq-1", type: "text", category: "bbq", body: "At long last, it's finally time to get cooking. You've gotten to know your smoker and you've sourced or seasoned the best wood you can possibly find." },
  { id: "bbq-2", type: "text", category: "bbq", body: "Life is too short for bad BBQ!" },
  { id: "bbq-3", type: "text", category: "bbq", body: "I tell people I'm living the dream, because I've turned my hobby into a job." },
  { id: "bbq-5", type: "text", category: "bbq", body: "To us, it's all about cooking delicious food and taking pride in everything we cook." },
  { id: "bbq-6", type: "text", category: "bbq", body: "But the fact that in Texas barbecue, you're taking one of the worst pieces of the animal and converting it into one of the best is a miracle itself." },
  { id: "bbq-7", type: "text", category: "bbq", body: "Sure, I was poor. But barbecue has never been a rich man's pleasure. It's always been a culture of thrift." },
  { id: "bbq-8", type: "text", category: "bbq", body: "I think it's key that you buy the best thing that you can afford." },
  { id: "bbq-9", type: "text", category: "bbq", body: "You learn from your mistakes and you just keep going and trying to do the best you can." },
  { id: "bbq-10", type: "text", category: "bbq", body: "A little beef tallow on the cutting board makes for those sexy slices." },
  { id: "bbq-11", type: "text", category: "bbq", body: "I am an absolute insatiable learner. I love to learn more than anything in the world." },
  { id: "bbq-12", type: "text", category: "bbq", body: "There is a saying in my industry, you buy the meat, not the sauce." },
  { id: "bbq-13", type: "text", category: "bbq", body: "I've always looked at myself as a student of BBQ, because no matter how long you've been doing it, there's always something else to learn." },
  { id: "bbq-14", type: "text", category: "bbq", body: "You can't make a fake fire." },
  { id: "bbq-15", type: "text", category: "bbq", body: "If the temperatures are up and down, it's pretty likely that your firewood is too big, so it's robbing energy from the fire to get to a combustion point." },
  { id: "bbq-16", type: "text", category: "bbq", body: "With steak, the worst thing you can do is overcook it." },
  { id: "bbq-17", type: "text", category: "bbq", body: "Like Traeger, I subscribe to the all-natural BBQ philosophy. The hardwood taste and authentic flavors from Traeger's wood fire and wood pellets just can't be beat." },
  { id: "bbq-18", type: "text", category: "bbq", body: "Barbecue feeds your soul because it brings people together." },
  { id: "bbq-19", type: "text", category: "bbq", body: "I do not say I'm lucky. I work too hard to be lucky." },
  { id: "bbq-21", type: "text", category: "bbq", body: "Great brisket comes down to three key factors: 1) Preparation — trim the excess fat. 2) Patience — hold a consistent temperature. 3) Rest — allow the meat to relax. Follow these steps for optimal results." },
  { id: "bbq-24", type: "text", category: "bbq", body: "Don’t drown good meat in rub until it tastes like a spice cabinet fell down the stairs. Salt, pepper, heat, smoke, and restraint will get you invited back." },
  { id: "bbq-35", type: "text", category: "bbq", body: "Tinfoil is a crutch, but peach butcher paper is a pitmaster's best friend. It breathes just enough to keep your crust nice and crunchy while holding in those essential juices. Trust the process and don't rush the wrap." },
  { id: "bbq-37", type: "text", category: "bbq", body: "In today's world, barbecue is more than just cooking meat over fire. It is a journey that brings people together and nourishes the soul, one tender bite at a time." },
  { id: "bbq-38", type: "text", category: "bbq", body: "Great brisket isn't just about heat; it's about patience, respect, and an unwavering devotion to the craft." },
  { id: "bbq-40", type: "text", category: "bbq", body: "At the end of the day, smoking meat is about more than flavor. It's about connection, tradition, and the stories we share around the table." },
  { id: "business-1", type: "text", category: "business", body: "Discipline equals freedom." },
  { id: "business-2", type: "text", category: "business", body: "It's not what you preach, it's what you tolerate." },
  { id: "business-3", type: "text", category: "business", body: "There are no bad teams, only bad leaders." },
  { id: "business-4", type: "text", category: "business", body: "When setting expectations, no matter what has been said or written, if substandard performance is accepted and no one is held accountable—if there are no consequences—that poor performance becomes the new standard." },
  { id: "business-5", type: "text", category: "business", body: "Good is the enemy of great. And that is one of the key reasons why we have so little that becomes great." },
  { id: "business-6", type: "text", category: "business", body: "Greatness is not a function of circumstance. Greatness, it turns out, is largely a matter of conscious choice, and discipline." },
  { id: "business-7", type: "text", category: "business", body: "Great vision without great people is irrelevant." },
  { id: "business-8", type: "text", category: "business", body: "You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you." },
  { id: "business-9", type: "text", category: "business", body: "Most people do not listen with the intent to understand; they listen with the intent to reply." },
  { id: "business-10", type: "text", category: "business", body: "People don't buy what you do; they buy why you do it." },
  { id: "business-14", type: "text", category: "business", body: "The market doesn’t care about your legacy strategy or how successful your previous product launch was. Disruption happens when an organization becomes too comfortable protecting past wins instead of cannibalizing its own business model to innovate. Stay paranoid, stay curious, and keep executing." },
  { id: "business-16", type: "text", category: "business", body: "You're absolutely right, and I apologize for the confusion. That's a great point about retention, and you've clearly thought deeply about this. Building on your excellent observation, psychological safety really is the foundation here." },
  { id: "business-20", type: "text", category: "business", body: "Your calendar is a confession. It reveals what you reward, what you avoid, and what you are accidentally teaching everyone else to value." },
  { id: "disney-1", type: "text", category: "disney", body: "You have forgotten who you are and so have forgotten me. Look inside yourself, Simba. You are more than what you have become. You must take your place in the Circle of Life." },
  { id: "disney-2", type: "text", category: "disney", body: "Everything you see exists together in a delicate balance. As king, you need to understand that balance and respect all the creatures, from the crawling ant to the leaping antelope." },
  { id: "disney-3", type: "text", category: "disney", body: "Look, over in that house is a kid who thinks you are the greatest, and it's not because you're a Space Ranger, pal. It's because you're a toy. You are his toy." },
  { id: "disney-4", type: "text", category: "disney", body: "You are a sad, strange little man, and you have my pity. Farewell." },
  { id: "disney-5", type: "text", category: "disney", body: "Well, you can't never let anything happen to him. Then nothing would ever happen to him. Not much fun for little Harpo." },
  { id: "disney-6", type: "text", category: "disney", body: "If he could learn to love another and earn her love in return by the time the last petal fell, then the spell would be broken. If not, he would be doomed to remain a beast for all time." },
  { id: "disney-7", type: "text", category: "disney", body: "Dishonor! Dishonor on your whole family! Make a note of this: dishonor on you, dishonor on your cow!" },
  { id: "disney-8", type: "text", category: "disney", body: "The flower that blooms in adversity is the most rare and beautiful of all. You don't meet a girl like that every dynasty." },
  { id: "disney-9", type: "text", category: "disney", body: "Some people are worth melting for. Just maybe not right this second." },
  { id: "disney-10", type: "text", category: "disney", body: "Not everyone can become a great artist, but a great artist can come from anywhere. It is difficult to imagine more humble origins than those of the genius now cooking at Gusteau's." },
  { id: "disney-11", type: "text", category: "disney", body: "You made it! Go! Go save Riley! Take her to the moon for me… okay?" },
  { id: "disney-12", type: "text", category: "disney", body: "It's kind of fun to do the impossible." },
  { id: "disney-18", type: "text", category: "disney", body: "Hurrying won't make the winter pass any faster, my little friend, as every single snowflake has its own special time to dance. Sit here by the hearth with me and let the frost paint its pictures on the windowpanes. Spring always knows exactly when to arrive." },
  { id: "speech-1", type: "text", category: "speech", body: "There are these two young fish swimming along and they happen to meet an older fish swimming the other way, who nods at them and says 'Morning, boys. How's the water?' And the two young fish swim on for a bit, and then eventually one of them looks over at the other and goes 'What the hell is water?'" },
  { id: "speech-2", type: "text", category: "speech", body: "The point of the fish story is merely that the most obvious, important realities are often the ones that are hardest to see and talk about." },
  { id: "speech-3", type: "text", category: "speech", body: "With your college diploma you now have a crushing advantage over 8% of the workforce. I'm talking about dropout losers like Bill Gates, Steve Jobs, and Mark Zuckerberg." },
  { id: "speech-4", type: "text", category: "speech", body: "I went from being in the center of the grid to not only off the grid, but underneath the coffee table that the grid sits on, lost in the shag carpeting that is underneath the coffee table supporting the grid." },
  { id: "speech-5", type: "text", category: "speech", body: "And, if by chance you have a miserable day, you will come home to a bed that is made — that you made — and a made bed gives you encouragement that tomorrow will be better. If you want to change the world, start off by making your bed." },
  { id: "speech-6", type: "text", category: "speech", body: "If you make your bed every morning you will have accomplished the first task of the day. It will give you a small sense of pride, and it will encourage you to do another task and another and another." },
  { id: "speech-7", type: "text", category: "speech", body: "Death is very likely the single best invention of Life. It is Life's change agent. It clears out the old to make way for the new." },
  { id: "speech-8", type: "text", category: "speech", body: "And I have always wished that for myself. And now, as you graduate to begin anew, I wish that for you. Stay Hungry. Stay Foolish." },
  { id: "speech-12", type: "text", category: "speech", body: "Do not let the fear of making a mistake paralyze your ambition, because every failure is simply a tuition payment toward your future wisdom. The most extraordinary lives are rarely linear; they are messy, unpredictable, and defined by the moments someone chose to get back up. Write a story worth telling." },
  { id: "movies-1", type: "text", category: "movies", body: "This is our most desperate hour. Help me, Obi-Wan Kenobi. You're my only hope." },
  { id: "movies-2", type: "text", category: "movies", body: "That's no moon. It's a space station." },
  { id: "movies-3", type: "text", category: "movies", body: "I find your lack of faith disturbing." },
  { id: "movies-4", type: "text", category: "movies", body: "These aren't the droids you're looking for." },
  { id: "movies-5", type: "text", category: "movies", body: "No! Try not. Do... or do not. There is no try." },
  { id: "movies-6", type: "text", category: "movies", body: "No. I am your father." },
  { id: "movies-7", type: "text", category: "movies", body: "Never tell me the odds!" },
  { id: "movies-8", type: "text", category: "movies", body: "\"I love you.\" \"I know.\"" },
  { id: "movies-9", type: "text", category: "movies", body: "Hello there." },
  { id: "movies-10", type: "text", category: "movies", body: "Genius, billionaire, playboy, philanthropist." },
  { id: "movies-11", type: "text", category: "movies", body: "That's my secret, Cap. I'm always angry." },
  { id: "movies-12", type: "text", category: "movies", body: "Puny god." },
  { id: "movies-13", type: "text", category: "movies", body: "Even when I had nothing, I had Bucky." },
  { id: "movies-14", type: "text", category: "movies", body: "Mr. Stark, I don't feel so good. I don't want to go. I don't want to go, sir. Please. I'm sorry." },
  { id: "movies-15", type: "text", category: "movies", body: "Perfectly balanced, as all things should be." },
  { id: "movies-16", type: "text", category: "movies", body: "Part of the journey is the end." },
  { id: "movies-17", type: "text", category: "movies", body: "And I... am... Iron Man." },
  { id: "movies-18", type: "text", category: "movies", body: "Avengers... assemble." },
  { id: "movies-19", type: "text", category: "movies", body: "I'm a mog: half man, half dog. I'm my own best friend!" },
  { id: "movies-20", type: "text", category: "movies", body: "\"I am your father's brother's nephew's cousin's former roommate.\" \"What's that make us?\" \"Absolutely nothing!\"" },
  { id: "movies-21", type: "text", category: "movies", body: "What's the matter, Colonel Sandurz? Chicken?!" },
  { id: "movies-22", type: "text", category: "movies", body: "There's only one man who would dare give me the raspberry: Lone Starr!" },
  { id: "movies-23", type: "text", category: "movies", body: "\"We were told to comb the desert, so we're combing it!\" \"We ain't found shit!\"" },
  { id: "movies-24", type: "text", category: "movies", body: "\"What happened to then?\" \"We passed then.\" \"When?\" \"Just now.\"" },
  { id: "movies-26", type: "text", category: "movies", body: "This was never about the throne, the crown, or the kingdom. It was about something far greater: the soul of every world that ever dared to dream." },
  { id: "movies-27", type: "text", category: "movies", body: "Together we will harness the storm, forge a new dawn, and unleash a power this universe has never witnessed." },
  { id: "movies-30", type: "text", category: "movies", body: "Victory is not measured in the battles we win, but in the lives we choose to protect along the way." },
  { id: "movies-32", type: "text", category: "movies", body: "Surrender now, and I may yet allow you to truly, deeply understand the profound mercy of which I am capable." },
  { id: "movies-35", type: "text", category: "movies", body: "Every great empire begins with a single choice, and today, my friends, we choose to delve into legend." },
  { id: "movies-36", type: "text", category: "movies", body: "They told me a machine could never love, never grieve, never truly hope. And yet, here I stand, profoundly and irrevocably alive." },
  { id: "genx-1", type: "text", category: "genx", body: "\"Surely you can't be serious.\" \"I am serious. And don't call me Shirley.\"" },
  { id: "genx-2", type: "text", category: "genx", body: "So I've got that going for me, which is nice." },
  { id: "genx-3", type: "text", category: "genx", body: "Back off, man. I'm a scientist." },
  { id: "genx-4", type: "text", category: "genx", body: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it." },
  { id: "genx-5", type: "text", category: "genx", body: "The 1961 Ferrari 250 GT California. Less than a hundred were made." },
  { id: "genx-6", type: "text", category: "genx", body: "My name is Inigo Montoya. You killed my father. Prepare to die." },
  { id: "genx-7", type: "text", category: "genx", body: "You keep using that word. I do not think it means what you think it means." },
  { id: "genx-8", type: "text", category: "genx", body: "What if there is no tomorrow? There wasn't one today." },
  { id: "genx-9", type: "text", category: "genx", body: "We're not worthy! We're not worthy!" },
  { id: "genx-10", type: "text", category: "genx", body: "So you're telling me there's a chance!" },
  { id: "genx-11", type: "text", category: "genx", body: "We get the warhead and hold the world ransom for... one million dollars!" },
  { id: "genx-12", type: "text", category: "genx", body: "Yeah, well, The Dude abides." },
  { id: "genx-13", type: "text", category: "genx", body: "I'm also gonna need you to go ahead and come in on Sunday, too, OK?" },
  { id: "genx-14", type: "text", category: "genx", body: "I want my two dollars!" },
  { id: "genx-15", type: "text", category: "genx", body: "They've got the golden arches. Mine are the golden arcs." },
  { id: "genx-16", type: "text", category: "genx", body: "It's all ball bearings nowadays." },
  { id: "genx-17", type: "text", category: "genx", body: "Nothing to see here. Please disperse!" },
  { id: "genx-18", type: "text", category: "genx", body: "\"Looking good, Billy Ray!\" \"Feeling good, Louis!\"" },
  { id: "genx-19", type: "text", category: "genx", body: "In today's fast-paced academic landscape, one must ask: is skipping school truly wrong, or is it simply a bold reallocation of one's personal time?" },
  { id: "genx-20", type: "text", category: "genx", body: "This isn't merely a golf tournament. It's a chance for one groundskeeper to finally be seen." },
  { id: "genx-21", type: "text", category: "genx", body: "Caddying taught me patience. It taught me humility. And it taught me the value of hard work." },
  { id: "genx-23", type: "text", category: "genx", body: "Before we toilet-paper the principal's house, let's delve into the realm of what could possibly go wrong." },
  { id: "genx-25", type: "text", category: "genx", body: "You asked whether I ate the last slice of pizza. That's a great question. Whether I ate the last slice of pizza is certainly worth examining." },
  { id: "genx-27", type: "text", category: "genx", body: "So I drove the golf cart into the pond, the cooler floated away, and my boss watched the whole thing. In the end, we all learned something about ourselves that day." },
  { id: "genx-28", type: "text", category: "genx", body: "My uncle's chili was truly spicy. Deeply, profoundly spicy. Everyone at the table was significantly affected." },
  { id: "genx-30", type: "text", category: "genx", body: "Excuse me, ghost. I don't wish to be rude, but you are currently inside our refrigerator, and several of us would prefer that you were not." },
  { id: "genx-35", type: "text", category: "genx", body: "You can't be nervous and hungry at the same time. That's science. Eat the shrimp." },
  { id: "millennial-1", type: "text", category: "millennial", body: "Moisture is the essence of wetness, and wetness is the essence of beauty." },
  { id: "millennial-2", type: "text", category: "millennial", body: "The best way to spread Christmas cheer is singing loud for all to hear." },
  { id: "millennial-3", type: "text", category: "millennial", body: "I just like to smile. Smiling's my favorite." },
  { id: "millennial-4", type: "text", category: "millennial", body: "I caught you a delicious bass." },
  { id: "millennial-5", type: "text", category: "millennial", body: "Girls only want boyfriends who have great skills." },
  { id: "millennial-6", type: "text", category: "millennial", body: "On Wednesdays, we wear pink." },
  { id: "millennial-7", type: "text", category: "millennial", body: "Gretchen, stop trying to make \"fetch\" happen. It's not going to happen." },
  { id: "millennial-8", type: "text", category: "millennial", body: "I don't know how to put this, but I'm kind of a big deal." },
  { id: "millennial-9", type: "text", category: "millennial", body: "If you ain't first, you're last." },
  { id: "millennial-10", type: "text", category: "millennial", body: "If you can dodge a wrench, you can dodge a ball." },
  { id: "millennial-11", type: "text", category: "millennial", body: "I'm watching you, Wazowski. Always watching. Always." },
  { id: "millennial-12", type: "text", category: "millennial", body: "Ogres are like onions. Onions have layers. Ogres have layers." },
  { id: "millennial-13", type: "text", category: "millennial", body: "\"Did we just become best friends?\" \"Yep.\"" },
  { id: "millennial-14", type: "text", category: "millennial", body: "No one knows what it means, but it's provocative. It gets the people going." },
  { id: "millennial-15", type: "text", category: "millennial", body: "It's not a man-purse. It's called a satchel. Indiana Jones wears one." },
  { id: "millennial-16", type: "text", category: "millennial", body: "I'm gonna need you to go ahead and come in tomorrow. So if you could be here around nine, that would be great." },
  { id: "millennial-17", type: "text", category: "millennial", body: "You're tacky, and I hate you." },
  { id: "millennial-18", type: "text", category: "millennial", body: "Help me, I'm poor." },
  { id: "millennial-19", type: "text", category: "millennial", body: "This isn't just a chili cook-off. It's a statement about who we are as a family, and I intend to make that statement." },
  { id: "millennial-20", type: "text", category: "millennial", body: "I live by three rules: never quit, never explain, and never wear socks with sandals." },
  { id: "millennial-21", type: "text", category: "millennial", body: "In today's fast-paced backyard environment, we have to ask ourselves whether we are ready for this water balloon fight." },
  { id: "millennial-22", type: "text", category: "millennial", body: "We lost the van, we lost the trophy, and I lost one shoe. But in the end, what we really found out there was each other." },
  { id: "millennial-23", type: "text", category: "millennial", body: "Gary is a deeply unpleasant individual, and I find his behavior profoundly disappointing." },
  { id: "millennial-24", type: "text", category: "millennial", body: "This sheet cake is a testament to what a team can achieve when we leverage our collective strengths." },
  { id: "millennial-25", type: "text", category: "millennial", body: "I'm terribly sorry to interrupt, and I do apologize for the poor timing, but the kitchen is on fire." },
  { id: "millennial-29", type: "text", category: "millennial", body: "\"Where is the cake?\" \"Where is the cake. That's a great question, and I do want to address it directly.\"" },
  { id: "millennial-31", type: "text", category: "millennial", body: "I'm not mad. I'm just going to go sit in the car for a while with the radio off." },
  { id: "millennial-32", type: "text", category: "millennial", body: "\"You wore a tuxedo to a pool party.\" \"I wore a tuxedo to a pool party, and I stand by it.\"" },
  { id: "millennial-33", type: "text", category: "millennial", body: "He's not my best friend. He's my emergency contact. There's a difference, and I'm not going to explain it." },
  { id: "millennial-34", type: "text", category: "millennial", body: "\"It's a group project, man.\" \"Correct. And I brought a laminated agenda.\"" },
  { id: "millennial-35", type: "text", category: "millennial", body: "I have never lost a bet. I have, on a few occasions, agreed to a different bet about halfway through." },
  { id: "genz-1", type: "text", category: "genz", body: "I only work in black. And sometimes, very, very dark gray." },
  { id: "genz-3", type: "text", category: "genz", body: "All right, let's do this one last time. My name is Peter Parker." },
  { id: "genz-4", type: "text", category: "genz", body: "You won't. It's a leap of faith. That's all it is, Miles." },
  { id: "genz-5", type: "text", category: "genz", body: "Yeah, no, don't put me down for cardio." },
  { id: "genz-6", type: "text", category: "genz", body: "I do hope you keep me in mind for any future game nights." },
  { id: "genz-7", type: "text", category: "genz", body: "\"You guys don't even care about school.\" \"No, we just don't only care about school.\"" },
  { id: "genz-8", type: "text", category: "genz", body: "Maximum effort." },
  { id: "genz-9", type: "text", category: "genz", body: "The only thing I do know is that we have to be kind. Please, be kind, especially when we don't know what's going on." },
  { id: "genz-13", type: "text", category: "genz", body: "We're a team now. And being a team means trusting each other, believing in each other, and occasionally stealing a van together." },
  { id: "genz-15", type: "text", category: "genz", body: "Guys. Guys. Okay, now that I have everyone's full and undivided attention, I would like to formally propose that we absolutely, positively, one hundred percent do not do that again." },
  { id: "genz-17", type: "text", category: "genz", body: "And that, my friends, is how you turn a total disaster into a slightly smaller disaster. Teamwork." },
  { id: "genz-18", type: "text", category: "genz", body: "Okay. New plan. Same as the old plan, but this time we run." },
  { id: "genz-19", type: "text", category: "genz", body: "You said you had a plan. You did not say the plan was a shopping cart." },
  { id: "genz-20", type: "text", category: "genz", body: "I'm not scared. My legs are scared. There's a difference and I'd rather not get into it right now." },
  { id: "alpha-1", type: "text", category: "alpha", body: "Rats along his back. When he calls your name, it all fades to black." },
  { id: "alpha-2", type: "text", category: "alpha", body: "But Aunt Lucy said, “If we're kind and polite, the world will be right.”" },
  { id: "alpha-3", type: "text", category: "alpha", body: "He's so fluffy, I'm gonna die!" },
  { id: "alpha-4", type: "text", category: "alpha", body: "And I don't mean it metaphorically or rhetorically or poetically or theoretically or in any other fancy way. I'm Death, straight up." },
  { id: "alpha-5", type: "text", category: "alpha", body: "If you start singing, I'm gonna throw up." },
  { id: "alpha-6", type: "text", category: "alpha", body: "“In today's fast-paced forest landscape, snack security is more important than ever,” announced the squirrel from the top of the picnic table. “Which is why I will now be taking that sandwich.”" },
  { id: "alpha-7", type: "text", category: "alpha", body: "“This isn't just a snowball fight,” said the penguin, adjusting his tiny scarf. “It's a chance to build something bigger than ourselves.”" },
  { id: "alpha-8", type: "text", category: "alpha", body: "“Before we delve into who ate the cake,” said the hamster, “let us take a moment to appreciate the rich tapestry of crumbs on this floor. Truly a testament to a family that eats together.”" },
  { id: "genx-36", type: "text", category: "genx", body: "We hid the entire pep band in the gym storage closet for forty minutes. They came out the wrong door, still playing, and marched straight into somebody's wedding. Which just goes to show, the plans that fall apart are the ones you keep forever." },
  { id: "movies-49", type: "text", category: "movies", body: "\"Reactor's at a hundred percent.\" \"What happens after a hundred?\" \"The manual stops at a hundred. There's just a phone number.\" Funny how the moments that terrify us are the ones that show us who we really are." },
  { id: "alpha-11", type: "text", category: "alpha", body: "\"Is everybody buckled?\" \"Yep.\" \"Is the dog buckled?\" \"The dog is driving.\" \"The dog is WHAT?\" Turns out the vacation we needed was never the one printed on the map." },
  { id: "bbq-41", type: "text", category: "bbq", body: "Pulled the pork butt off the smoker tonight and I am wholly, thoroughly, and completely satisfied with how it turned out. The flavor was immensely flavorful. Highly recommend this cook to anyone." },
  { id: "disney-25", type: "text", category: "disney", body: "“Do not fret, little one,” said the badger, patting the acorn with one paw. “I am entirely, sincerely, and wholeheartedly certain that everything is going to work out extraordinarily well in the end.”" },
  { id: "speech-17", type: "text", category: "speech", body: "Graduates, I am incredibly, tremendously, and unbelievably proud of each and every one of you. What all of you have accomplished here is genuinely, authentically remarkable." },
  { id: "movies-50", type: "text", category: "movies", body: "Am I in? Buddy, I am fundamentally, comprehensively, and permanently on board. I have never in my entire life been more on board with a plan than I am with this plan right now." },
  { id: "movies-51", type: "text", category: "movies", body: "Captain, this vessel and everyone aboard her are utterly, unequivocally, irreversibly doomed. I recommend we respond with maximum urgency." },
  { id: "bbq-42", type: "text", category: "bbq", body: "A backyard cook is not measured in pounds of pork. It is measured in the trust of everyone standing there holding a paper plate." },
  { id: "business-25", type: "text", category: "business", body: "Thanks for flagging this! Honestly, this thread was never about the parking spots. It was about who we choose to be when the lot fills up." },
  { id: "speech-18", type: "text", category: "speech", body: "The gown you are wearing today is not merely a rental, but the final costume of the person you used to be." },
  { id: "genx-37", type: "text", category: "genx", body: "This is bigger than a bowling trophy, Dale. This is about whether anybody in this town still believes in anything." },
  { id: "alpha-12", type: "text", category: "alpha", body: "“What started as a hunt for one missing sock,” the raccoon said quietly, “had become a hunt for who we are as a family.”" },
  { id: "bbq-43", type: "text", category: "bbq", body: "Hi all, hope everyone is having a wonderful Saturday! So sorry to bother the group, but a very large dog has run off with the entire brisket and is heading toward the creek. Only if anyone happens to be free. No pressure either way!" },
  { id: "business-26", type: "text", category: "business", body: "Thank you all so much for your hard work this quarter, and I truly appreciate everyone’s dedication. I did want to gently flag, when you have a moment, that the entire customer database was deleted this morning. Great effort all around!" },
  { id: "disney-26", type: "text", category: "disney", body: "“Excuse me, Mister Hawk,” said the rabbit as the shadow closed in, “I hate to be a bother, and your talons really are lovely, but I was rather hoping to keep my afternoon free.”" },
  { id: "speech-19", type: "text", category: "speech", body: "I am told that siren means a tornado, and we will absolutely be heading to the basement shortly. Before we do, though, I would be remiss not to thank the faculty, the parents, and the wonderful volunteers who set up all of these chairs." },
  { id: "genx-38", type: "text", category: "genx", body: "I don’t mean to be a backseat driver, and you are doing wonderfully, but if it isn’t too much trouble, might we consider losing the eleven police cars? Whenever you get a chance. Truly no rush." },
  { id: "millennial-36", type: "text", category: "millennial", body: "Hi team, hope you are all well. Truly no big deal, and I am sure it was an honest mistake, but someone has eaten my labeled lunch three days running. Sending gratitude to whoever it was!" },
  { id: "alpha-13", type: "text", category: "alpha", body: "“I recognize that this is a very big feeling,” the dad said calmly while the toddler screamed in aisle nine, “and I want to sincerely thank you for sharing it with the entire store.”" },
  { id: "movies-52", type: "text", category: "movies", body: "Bridge, so sorry to bother you during shift change. I hate to be the bearer of bad news, but something enormous has come through the hull and it does not appear to be friendly. Take your time!" },
  { id: "bbq-44", type: "text", category: "bbq", body: "Certainly! Here are three excellent wood choices for pork: • Apple — mild and slightly sweet • Cherry — beautiful color • Hickory — bold and traditional. Happy smoking!" },
  { id: "business-27", type: "text", category: "business", body: "Hi Dana — great question! Regarding the 3pm: 1) Availability — my calendar is clear. 2) Preparation — I will review the deck beforehand. 3) Follow-up — I will circulate notes after. Let me know if you'd like me to expand on any of these." },
  { id: "disney-27", type: "text", category: "disney", body: "“There now, little fawn,” said the old owl. “Your feelings are completely valid. **Step 1: Breathe.** **Step 2: Name the fear.** **Step 3: Take one small step.** You've got this!”" },
  { id: "speech-20", type: "text", category: "speech", body: "Before you toss your caps, here are my key takeaways: 1) Be curious. 2) Be kind. 3) Be persistent. In summary, the future belongs to those who show up. Congratulations, graduates!" },
  { id: "genx-39", type: "text", category: "genx", body: "The cops are at the door. Okay — quick breakdown of our options: • Option A: the window • Option B: the laundry chute • Option C: honesty. Each has trade-offs. Thoughts?" },
  { id: "millennial-37", type: "text", category: "millennial", body: "**Summary:** I ate your leftovers. **Context:** I was hungry. **Impact:** Acknowledged. **Proposed remedy:** replacement by Sunday. Would you like me to elaborate on any section?" },
  { id: "alpha-14", type: "text", category: "alpha", body: "“Family meeting!” barked the dog. “Agenda item one: the mailman. Agenda item two: the vacuum. Agenda item three: snacks. I have also prepared a short recap for anyone joining late.”" },
  { id: "movies-53", type: "text", category: "movies", body: "Hull breach in ninety seconds. Here is the plan: Step 1) Seal deck four. Step 2) Reroute auxiliary power. Step 3) Get everyone off the bridge. Shall I proceed, or would you like me to adjust the sequence?" },
  { id: "speech-21", type: "text", category: "speech", body: "A quick toast, organized into three parts. **Part one: How they met.** **Part two: Why it works.** **Part three: The wish.** Please hold applause until the end of the outline." },
  { id: "bbq-45", type: "text", category: "bbq", body: "Q: Brisket has been stuck at 160 for four hours, do I wrap it? A: Let me make sure I have your question right. Your brisket has been stuck at 160 for four hours and you want to know whether to wrap it. Four hours is a meaningful stretch of time." },
  { id: "business-28", type: "text", category: "business", body: "Thanks for flagging this. To restate the question: you're asking whether we will make payroll on Friday. Whether we make payroll on Friday is absolutely the right thing to be focused on, and I want to give it the thoughtful response it deserves." },
  { id: "disney-28", type: "text", category: "disney", body: "“Owl, is the water still rising?” “Is the water still rising. What a thoughtful thing to ask, little one. Few creatures in this wood stop to wonder about the water at all, and here you are, wondering.”" },
  { id: "speech-22", type: "text", category: "speech", body: "A student stopped me last night and asked, “What do we do now?” What do you do now. I want to stay with that question a moment. It is a question, it is yours, and the fact that you asked it says everything about this class." },
  { id: "genx-40", type: "text", category: "genx", body: "“Which wire do I cut?” “Which wire do you cut. Terrific question. Honestly, one of the better ones anyone has asked me in this parking garage, and I have been down here since Tuesday.”" },
  { id: "millennial-38", type: "text", category: "millennial", body: "“Did you mail the invitations?” “Did I mail the invitations. Wow. Okay. That is exactly the question I would be asking if I were standing where you are standing, and I respect it enormously.”" },
  { id: "alpha-15", type: "text", category: "alpha", body: "“Dad, are we lost?” “Are we lost. Buddy, that is a big question, and I think it is one this whole family has earned the right to ask.” The van continued in the wrong direction." },
  { id: "movies-54", type: "text", category: "movies", body: "“How long until the core blows?” “How long until the core blows. Excellent question, Commander, and one that gets right to the heart of what every soul aboard this ship is feeling.”" },
  { id: "bbq-46", type: "text", category: "bbq", body: "What a fantastic question, and you're so right to push back — sorry for any mix-up on my end. Your instinct to run 225 is excellent. And if 275 feels better to you, I think that's a wonderful choice too and I completely agree." },
  { id: "business-29", type: "text", category: "business", body: "Susan, what a sharp callout — I should have caught that myself. Apologies for the confusion on slide four. I really love where your head is at here, and I'm happy to change the forecast to whatever number feels right to you." },
  { id: "disney-29", type: "text", category: "disney", body: "“Oh, you are SO wise, little one,” chirped the squirrel, bowing low. “And I'm terribly sorry if I upset you. Whatever you think the golden acorn means, that is exactly what it means. What a beautiful mind you have.”" },
  { id: "speech-23", type: "text", category: "speech", body: "Before I begin, let me just say what an incredible audience you are. And if anything I say tonight lands wrong, I apologize in advance, and you are almost certainly right. Honestly, any one of you could give this speech better than me." },
  { id: "genx-41", type: "text", category: "genx", body: "“You call that a parking job?” “Wow, okay, that is a really fair observation and I'm sorry. You clearly know a lot about parking, way more than I do. I would genuinely love your notes.”" },
  { id: "millennial-39", type: "text", category: "millennial", body: "“You are hands down the smartest person in this office, and I say that with total respect. Also, I'm sorry. I don't know what for yet, but I can feel that I'm sorry, and you were right about everything.”" },
  { id: "alpha-16", type: "text", category: "alpha", body: "“I'm sorry, I'm sorry!” beeped the little robot vacuum. “You're the best kid in this whole house and your plan is so much better than mine. Please don't be mad. We'll do it your way, even the part with the lava.”" },
  { id: "movies-55", type: "text", category: "movies", body: "“Captain, the reactor is past critical.” “Cut the coolant.” “Excellent instinct, Captain, and I'm sorry for questioning you. Cutting coolant now. What a thoughtful decision to make under this much pressure.”" },
  { id: "business-30", type: "text", category: "business", body: "“My package never arrived.” “You are so right to reach out, and what a clearly written message. I'm very sorry for the trouble. That said, if you feel the package did arrive, I fully support that as well. Thank you for being such a valued partner.”" },
  { id: "business-31", type: "text", category: "business", body: "Appreciate the patience here. The launch moved for three reasons: bandwidth, timing, and a real commitment to quality. Happy to walk through any of it live." },
  { id: "disney-30", type: "text", category: "disney", body: "“An acorn only needs three things to become an oak,” said the old badger, patting the sapling. “Good soil, steady rain, and the courage to believe in itself.”" },
  { id: "movies-56", type: "text", category: "movies", body: "The reactor breach gives us four minutes. Getting off this ship will take three things: steady hands, a clear channel, and faith in each other. Move." },
  { id: "bbq-47", type: "text", category: "bbq", body: "In an era of ever-shifting food trends, it is worth taking a moment to reflect on what really matters out here at the grill. Somebody has walked off with my tongs again." },
  { id: "business-32", type: "text", category: "business", body: "As we navigate an increasingly complex scheduling landscape, it is important to step back and think about how we align on shared availability. Yes, 2:00 works for me." },
  { id: "disney-31", type: "text", category: "disney", body: "“In a world where the pond changes a little more with every passing season,” the duck said gravely from the top of the flat rock, “one thing has stayed the same. That is my rock, and you are standing on it.”" },
  { id: "speech-24", type: "text", category: "speech", body: "In today's ever-evolving campus environment, few moments carry the weight of the one we share this afternoon. Before we begin, the owner of the silver sedan blocking the loading dock needs to move it now." },
  { id: "millennial-40", type: "text", category: "millennial", body: "At a moment when the modern wedding reception asks more of us than ever, we owe each other some honesty. The open bar closes in nine minutes and Dave is already crying in the parking lot." },
  { id: "movies-57", type: "text", category: "movies", body: "Amid the ever-accelerating pace of interstellar conflict, it is worth pausing to consider the bigger picture. Also, the reactor breaches in forty seconds and somebody welded the door behind you." },
  { id: "bbq-48", type: "text", category: "bbq", body: "Fired up the offset at 4 a.m. to elevate a humble pork shoulder into something the whole cul-de-sac will remember." },
  { id: "business-33", type: "text", category: "business", body: "Thanks for flagging! Happy to unlock some time Thursday to align on the potluck sign-up sheet." },
  { id: "disney-32", type: "text", category: "disney", body: "“The river has risen again,” said the old raccoon, resting a paw on the boy's shoulder. “Together, we must navigate the challenges ahead.”" },
  { id: "speech-25", type: "text", category: "speech", body: "Graduates, beyond these doors awaits a myriad of opportunities, each one ready for you to seize it." },
  { id: "genx-42", type: "text", category: "genx", body: "Trust me, man. Sneaking into the faculty lounge is the pivotal moment of our entire senior year." },
  { id: "alpha-17", type: "text", category: "alpha", body: "The eight-year-old folded her arms on the minivan seat. “All I'm asking,” she said, “is that this family foster a more open dialogue about bedtime.”" },
];

export const PUBLIC_BY_ID: Record<string, PublicQuestion> = Object.fromEntries(
  PUBLIC_QUESTIONS.map((q) => [q.id, q]),
);
