import type { PublicQuestion } from "./types";

// PROMPTS ONLY — no answers. Safe to ship to the browser. Generated from
// lib/questions.server.ts by scripts/gen-public-questions.ts — do not edit by hand.
export const PUBLIC_QUESTIONS: PublicQuestion[] = [
  { id: "bbq-1", type: "text", category: "bbq", body: "At long last, it's finally time to get cooking. You've gotten to know your smoker and you've sourced or seasoned the best wood you can possibly find." },
  { id: "bbq-2", type: "text", category: "bbq", body: "Life is too short for bad BBQ!" },
  { id: "bbq-3", type: "text", category: "bbq", body: "I tell people I'm living the dream, because I've turned my hobby into a job." },
  { id: "bbq-5", type: "text", category: "bbq", body: "To us, it's all about cooking delicious food and taking pride in everything we cook." },
  { id: "bbq-6", type: "text", category: "bbq", body: "But the fact that in Texas barbecue, you're taking one of the worst pieces of the animal and converting it into one of the best is a miracle itself." },
  { id: "bbq-7", type: "text", category: "bbq", body: "Sure, I was poor. But barbecue has never been a rich man's pleasure. It's always been a culture of thrift." },
  { id: "bbq-8", type: "text", category: "bbq", body: "I think it's key that you buy the best thing that you can afford." },
  { id: "bbq-9", type: "text", category: "bbq", body: "You learn from your mistakes and you just keep going and trying to do the best you can." },
  { id: "bbq-10", type: "text", category: "bbq", body: "A little beef tallow on the cutting board makes for those sexy slices." },
  { id: "bbq-11", type: "text", category: "bbq", body: "I am an absolute insatiable learner. I love to learn more than anything in the world." },
  { id: "bbq-12", type: "text", category: "bbq", body: "There is a saying in my industry, you buy the meat, not the sauce." },
  { id: "bbq-13", type: "text", category: "bbq", body: "I've always looked at myself as a student of BBQ, because no matter how long you've been doing it, there's always something else to learn." },
  { id: "bbq-14", type: "text", category: "bbq", body: "You can't make a fake fire." },
  { id: "bbq-15", type: "text", category: "bbq", body: "If the temperatures are up and down, it's pretty likely that your firewood is too big, so it's robbing energy from the fire to get to a combustion point." },
  { id: "bbq-16", type: "text", category: "bbq", body: "With steak, the worst thing you can do is overcook it." },
  { id: "bbq-17", type: "text", category: "bbq", body: "Like Traeger, I subscribe to the all-natural BBQ philosophy. The hardwood taste and authentic flavors from Traeger's wood fire and wood pellets just can't be beat." },
  { id: "bbq-18", type: "text", category: "bbq", body: "Barbecue feeds your soul because it brings people together." },
  { id: "bbq-19", type: "text", category: "bbq", body: "I do not say I'm lucky. I work too hard to be lucky." },
  { id: "bbq-21", type: "text", category: "bbq", body: "Brisket doesn’t care about your schedule, and that’s the first lesson. Trim it clean, season it honest, and let the smoke do its slow little sermon." },
  { id: "bbq-22", type: "text", category: "bbq", body: "Smoke rings are pretty, but flavor pays the rent. If your bark has pepper bite, fat shimmer, and that campfire depth, nobody’s asking for a microscope." },
  { id: "bbq-23", type: "text", category: "bbq", body: "A pork shoulder is basically a trust exercise wrapped in butcher paper. Somewhere around hour six, it looks like nothing is happening, which means everything is happening." },
  { id: "bbq-24", type: "text", category: "bbq", body: "Don’t drown good meat in rub until it tastes like a spice cabinet fell down the stairs. Salt, pepper, heat, smoke, and restraint will get you invited back." },
  { id: "bbq-25", type: "text", category: "bbq", body: "Burgers need confidence, not choreography. Hot grate, cold meat, one good flip, and cheese melted just enough to start looking dangerous." },
  { id: "bbq-26", type: "text", category: "bbq", body: "I like ribs with a little tug, not falling off the bone like they gave up on themselves. Sauce goes on near the end, just enough to shine them up for company." },
  { id: "bbq-27", type: "text", category: "bbq", body: "The secret to good chicken thighs is patience and not poking at them every twelve seconds like a raccoon with a badge. Let the skin render, let the edges crisp, then bring in the glaze." },
  { id: "bbq-28", type: "text", category: "bbq", body: "I build my fire before I build my menu. Oak for beef, apple for pork, and a little hickory when I want the backyard to smell like it has opinions." },
  { id: "bbq-29", type: "text", category: "bbq", body: "If you’re looking at your watch, you’re doing it all wrong. Real Texas brisket doesn't care about your schedule, it only cares about the wood, the smoke, and the internal temp. Pull it when it jiggles like Jell-O and let it rest for at least two hours, period." },
  { id: "bbq-30", type: "text", category: "bbq", body: "That bark right there isn't burnt, it’s pure flavor built up over twelve hours of post oak smoke. The secret is keeping the fire clean and the rub heavy on the coarse black pepper. Slice it thick and let the juice do the talking." },
  { id: "bbq-31", type: "text", category: "bbq", body: "Look at that smoke ring definition on these pork ribs. They’ve got just enough bite to come clean off the bone without falling apart into mush. Hit 'em with a light glaze of sweet heat right at the end for that picture-perfect shine." },
  { id: "bbq-32", type: "text", category: "bbq", body: "Sunday mornings start at 4:00 AM around here, getting the firebox stoked and the ambient temp locked right at 225. There’s something peaceful about watching the smoke roll while the rest of the neighborhood is still asleep. Grab a coffee, it's gonna be a long, beautiful day." },
  { id: "bbq-33", type: "text", category: "bbq", body: "A lot of guys overcomplicate the rub, but honestly, kosher salt and cracked pepper are all a good piece of beef needs. Let the quality of the meat and the draft of your offset smoker do the heavy lifting. If the smoke is blue, you’re doing it right." },
  { id: "bbq-34", type: "text", category: "bbq", body: "We are officially locked and loaded for the weekend crowd, and these pork shoulders are already looking incredible. The fat cap is rendering down perfectly, basting the meat from the inside out. Get down here before the sold-out sign goes up." },
  { id: "bbq-35", type: "text", category: "bbq", body: "Tinfoil is a crutch, but peach butcher paper is a pitmaster's best friend. It breathes just enough to keep your crust nice and crunchy while holding in those essential juices. Trust the process and don't rush the wrap." },
  { id: "bbq-36", type: "text", category: "bbq", body: "You can buy the most expensive rig on the market, but you can’t buy patience. True barbecue is an art form of minor adjustments, feeling the heat, and listening to the sizzle on the deflector plate. Fire up the pits and let’s get to work." },
  { id: "bbq-37", type: "text", category: "bbq", body: "In today's world, barbecue is more than just cooking meat over fire. It is a journey that brings people together and nourishes the soul, one tender bite at a time." },
  { id: "bbq-38", type: "text", category: "bbq", body: "Great brisket isn't just about heat; it's about patience, respect, and an unwavering devotion to the craft." },
  { id: "bbq-39", type: "text", category: "bbq", body: "What separates a good pitmaster from a great one? The answer is simple: an unrelenting commitment to the fire." },
  { id: "bbq-40", type: "text", category: "bbq", body: "At the end of the day, smoking meat is about more than flavor. It's about connection, tradition, and the stories we share around the table." },
  { id: "business-1", type: "text", category: "business", body: "Discipline equals freedom." },
  { id: "business-2", type: "text", category: "business", body: "It's not what you preach, it's what you tolerate." },
  { id: "business-3", type: "text", category: "business", body: "There are no bad teams, only bad leaders." },
  { id: "business-4", type: "text", category: "business", body: "When setting expectations, no matter what has been said or written, if substandard performance is accepted and no one is held accountable—if there are no consequences—that poor performance becomes the new standard." },
  { id: "business-5", type: "text", category: "business", body: "Good is the enemy of great. And that is one of the key reasons why we have so little that becomes great." },
  { id: "business-6", type: "text", category: "business", body: "Greatness is not a function of circumstance. Greatness, it turns out, is largely a matter of conscious choice, and discipline." },
  { id: "business-7", type: "text", category: "business", body: "Great vision without great people is irrelevant." },
  { id: "business-8", type: "text", category: "business", body: "You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you." },
  { id: "business-9", type: "text", category: "business", body: "Most people do not listen with the intent to understand; they listen with the intent to reply." },
  { id: "business-10", type: "text", category: "business", body: "People don't buy what you do; they buy why you do it." },
  { id: "business-13", type: "text", category: "business", body: "True operational scale isn’t about working harder; it’s about decoupling your revenue growth from your headcount. When leaders focus on building repeatable frameworks rather than firefighting daily anomalies, the entire organization aligns. Focus on systems that empower autonomy, not bottlenecks that require permission." },
  { id: "business-14", type: "text", category: "business", body: "The market doesn’t care about your legacy strategy or how successful your previous product launch was. Disruption happens when an organization becomes too comfortable protecting past wins instead of cannibalizing its own business model to innovate. Stay paranoid, stay curious, and keep executing." },
  { id: "business-15", type: "text", category: "business", body: "Resilience isn't an innate personality trait; it’s an organizational muscle developed through navigating ambiguity. When milestones are missed, the instinct is often to assign blame, but the highest-performing cultures treat failures as data points for iterative improvement. Turn your post-mortems into launchpads." },
  { id: "business-16", type: "text", category: "business", body: "Empathy is often dismissed as a soft skill, but it is actually the hardest and most lucrative tool in a modern executive's toolkit. When employees feel genuinely understood and psychologically safe, retention skyrocketing follows naturally. Take care of your people, and they will relentlessly take care of your metrics." },
  { id: "business-17", type: "text", category: "business", body: "True leadership isn't validated by how many decisions you make, but by how many leaders you develop to make them instead. If your department paralyzes the moment you go on vacation, you haven’t built a team, you’ve built a dependency. Step back so your people can step up." },
  { id: "business-18", type: "text", category: "business", body: "We often mistake frantic activity for progress, but velocity without a clear direction is just noise. The best executives I’ve worked with spend more time listening to frontline friction than reviewing high-level slide decks. If you want to fix your culture, start by fixing the small things that drain your team's daily energy." },
  { id: "business-19", type: "text", category: "business", body: "Good leaders do not remove all friction; they remove the useless friction. Some tension sharpens the work, but bureaucracy just puts a velvet rope around progress." },
  { id: "business-20", type: "text", category: "business", body: "Your calendar is a confession. It reveals what you reward, what you avoid, and what you are accidentally teaching everyone else to value." },
  { id: "business-21", type: "text", category: "business", body: "The mistake many teams make is confusing alignment with agreement. Alignment means we know the decision, the tradeoff, and the owner, even if we would have chosen differently." },
  { id: "business-22", type: "text", category: "business", body: "Culture is not what gets printed on the wall; it is what people feel safe saying in the meeting. The real work of leadership is lowering the cost of honesty." },
  { id: "business-23", type: "text", category: "business", body: "Trust compounds slowly and spends quickly. Every missed follow-through is a small withdrawal, even when nobody says it out loud." },
  { id: "business-24", type: "text", category: "business", body: "A strategy that cannot survive contact with the frontline is not a strategy, it is office theater. The best leaders keep walking back to the people closest to the work." },
  { id: "disney-1", type: "text", category: "disney", body: "You have forgotten who you are and so have forgotten me. Look inside yourself, Simba. You are more than what you have become. You must take your place in the Circle of Life." },
  { id: "disney-2", type: "text", category: "disney", body: "Everything you see exists together in a delicate balance. As king, you need to understand that balance and respect all the creatures, from the crawling ant to the leaping antelope." },
  { id: "disney-3", type: "text", category: "disney", body: "Look, over in that house is a kid who thinks you are the greatest, and it's not because you're a Space Ranger, pal. It's because you're a toy. You are his toy." },
  { id: "disney-4", type: "text", category: "disney", body: "You are a sad, strange little man, and you have my pity. Farewell." },
  { id: "disney-5", type: "text", category: "disney", body: "Well, you can't never let anything happen to him. Then nothing would ever happen to him. Not much fun for little Harpo." },
  { id: "disney-6", type: "text", category: "disney", body: "If he could learn to love another and earn her love in return by the time the last petal fell, then the spell would be broken. If not, he would be doomed to remain a beast for all time." },
  { id: "disney-7", type: "text", category: "disney", body: "Dishonor! Dishonor on your whole family! Make a note of this: dishonor on you, dishonor on your cow!" },
  { id: "disney-8", type: "text", category: "disney", body: "The flower that blooms in adversity is the most rare and beautiful of all. You don't meet a girl like that every dynasty." },
  { id: "disney-9", type: "text", category: "disney", body: "Some people are worth melting for. Just maybe not right this second." },
  { id: "disney-10", type: "text", category: "disney", body: "Not everyone can become a great artist, but a great artist can come from anywhere. It is difficult to imagine more humble origins than those of the genius now cooking at Gusteau's." },
  { id: "disney-11", type: "text", category: "disney", body: "You made it! Go! Go save Riley! Take her to the moon for me… okay?" },
  { id: "disney-12", type: "text", category: "disney", body: "It's kind of fun to do the impossible." },
  { id: "disney-13", type: "text", category: "disney", body: "You see, a heart isn't judged by how much you love, but by how much you are loved by others in return. Even when the shadows grow long and the path ahead seems completely lost, that warmth will always show you the way home. Just take my hand and don't be afraid." },
  { id: "disney-14", type: "text", category: "disney", body: "It doesn't matter if you're made of tin, or wood, or fluff and stuffing, because real magic comes from what's beating inside your chest. When you love someone, you give them a piece of yourself that can never be broken or taken away. That's a promise that lasts forever." },
  { id: "disney-15", type: "text", category: "disney", body: "Change can be a little scary at first, kind of like stepping outside into a big, loud thunderstorm without an umbrella. But if we never let the rain fall, the flowers in the valley would never get a chance to grow. I think it’s time for us to see what’s waiting out there." },
  { id: "disney-16", type: "text", category: "disney", body: "They can take away our crowns, lock us in the highest towers, and banish us to the edge of the map, but they can never steal our dreams. As long as we have each other, we have a spark that can light up the darkest night. Now, let’s go show them what we're made of." },
  { id: "disney-17", type: "text", category: "disney", body: "The stars up there look so small, but I think they’re actually giant windows looking into all the places we haven't discovered yet. If we fly fast enough, maybe we can find a way right through them. We just have to hold on tight and never look down." },
  { id: "disney-18", type: "text", category: "disney", body: "Hurrying won't make the winter pass any faster, my little friend, as every single snowflake has its own special time to dance. Sit here by the hearth with me and let the frost paint its pictures on the windowpanes. Spring always knows exactly when to arrive." },
  { id: "disney-19", type: "text", category: "disney", body: "“Home isn’t the door,” the candle said, flickering proudly. “It’s who leaves a light on when you’re late.”" },
  { id: "disney-20", type: "text", category: "disney", body: "“The forest doesn’t give maps to people who already know everything,” the fox said. “It prefers the lost ones. They listen better.”" },
  { id: "disney-21", type: "text", category: "disney", body: "“Your song is still in there,” the whale murmured beneath the silver waves. “It just got buried under everyone else’s noise.”" },
  { id: "disney-22", type: "text", category: "disney", body: "“I’m not small,” said the mouse, adjusting his acorn helmet. “I’m travel-sized for destiny.”" },
  { id: "disney-23", type: "text", category: "disney", body: "“I tried to be perfect and accidentally became miserable,” said the little prince. “So tomorrow I’m going to be terrible at something and see if the sun still rises.”" },
  { id: "disney-24", type: "text", category: "disney", body: "Oh, great, another ancient, booby-trapped temple filled with spikes and bugs, because a regular walk in the woods would just be too boring. Don’t touch anything, especially not that giant, shiny ruby that is practically screaming 'grab me' right now. Wait, where did you go?" },
  { id: "speech-1", type: "text", category: "speech", body: "There are these two young fish swimming along and they happen to meet an older fish swimming the other way, who nods at them and says 'Morning, boys. How's the water?' And the two young fish swim on for a bit, and then eventually one of them looks over at the other and goes 'What the hell is water?'" },
  { id: "speech-2", type: "text", category: "speech", body: "The point of the fish story is merely that the most obvious, important realities are often the ones that are hardest to see and talk about." },
  { id: "speech-3", type: "text", category: "speech", body: "With your college diploma you now have a crushing advantage over 8% of the workforce. I'm talking about dropout losers like Bill Gates, Steve Jobs, and Mark Zuckerberg." },
  { id: "speech-4", type: "text", category: "speech", body: "I went from being in the center of the grid to not only off the grid, but underneath the coffee table that the grid sits on, lost in the shag carpeting that is underneath the coffee table supporting the grid." },
  { id: "speech-5", type: "text", category: "speech", body: "And, if by chance you have a miserable day, you will come home to a bed that is made — that you made — and a made bed gives you encouragement that tomorrow will be better. If you want to change the world, start off by making your bed." },
  { id: "speech-6", type: "text", category: "speech", body: "If you make your bed every morning you will have accomplished the first task of the day. It will give you a small sense of pride, and it will encourage you to do another task and another and another." },
  { id: "speech-7", type: "text", category: "speech", body: "Death is very likely the single best invention of Life. It is Life's change agent. It clears out the old to make way for the new." },
  { id: "speech-8", type: "text", category: "speech", body: "And I have always wished that for myself. And now, as you graduate to begin anew, I wish that for you. Stay Hungry. Stay Foolish." },
  { id: "speech-9", type: "text", category: "speech", body: "As you walk across this stage today, remember that your degree is not a final destination, but rather a key to doors you haven't even envisioned yet. The world doesn't need you to fit into the existing molds; it desperately needs you to shatter them and build something better. Go out there and make kindness your loudest attribute." },
  { id: "speech-10", type: "text", category: "speech", body: "We often spend our youth waiting for the perfect moment to start, waiting for a sign that we are finally ready to make our mark. The truth is, perfection is an illusion designed to keep you comfortable in the harbor of safety. Row away from the shore, embrace the storms, and realize you were ready all along." },
  { id: "speech-11", type: "text", category: "speech", body: "Look around this room at the people who supported you, wept with you, and pushed you to reach this milestone. No one achieves greatness in a vacuum, and our success is always a collective tapestry woven by those who believed in us. Carry their belief into the world and become that pillar for someone else." },
  { id: "speech-12", type: "text", category: "speech", body: "Do not let the fear of making a mistake paralyze your ambition, because every failure is simply a tuition payment toward your future wisdom. The most extraordinary lives are rarely linear; they are messy, unpredictable, and defined by the moments someone chose to get back up. Write a story worth telling." },
  { id: "speech-13", type: "text", category: "speech", body: "Your education has given you a voice, and with that voice comes the profound responsibility to speak for those who are currently unheard. Do not use your talents merely to climb the ladders of corporate success; use them to widen the base so more people can climb with you. True legacy is measured by what you give back." },
  { id: "speech-14", type: "text", category: "speech", body: "Today marks the end of a chapter, but the pen is now entirely in your hands for the rest of the book. Do not let the cynicism of the world dampen the fierce optimism that brought you to this very moment. Be bold, stay curious, and never apologize for dreaming too big." },
  { id: "speech-15", type: "text", category: "speech", body: "You are not here because the path was clear. You are here because you kept walking when the map turned into fog." },
  { id: "speech-16", type: "text", category: "speech", body: "Do not mistake certainty for wisdom. The people who change the world are often the ones willing to ask one more question when everyone else has packed up the chairs." },
  { id: "movies-1", type: "text", category: "movies", body: "This is our most desperate hour. Help me, Obi-Wan Kenobi. You're my only hope." },
  { id: "movies-2", type: "text", category: "movies", body: "That's no moon. It's a space station." },
  { id: "movies-3", type: "text", category: "movies", body: "I find your lack of faith disturbing." },
  { id: "movies-4", type: "text", category: "movies", body: "These aren't the droids you're looking for." },
  { id: "movies-5", type: "text", category: "movies", body: "No! Try not. Do... or do not. There is no try." },
  { id: "movies-6", type: "text", category: "movies", body: "No. I am your father." },
  { id: "movies-7", type: "text", category: "movies", body: "Never tell me the odds!" },
  { id: "movies-8", type: "text", category: "movies", body: "\"I love you.\" \"I know.\"" },
  { id: "movies-9", type: "text", category: "movies", body: "Hello there." },
  { id: "movies-10", type: "text", category: "movies", body: "Genius, billionaire, playboy, philanthropist." },
  { id: "movies-11", type: "text", category: "movies", body: "That's my secret, Cap. I'm always angry." },
  { id: "movies-12", type: "text", category: "movies", body: "Puny god." },
  { id: "movies-13", type: "text", category: "movies", body: "Even when I had nothing, I had Bucky." },
  { id: "movies-14", type: "text", category: "movies", body: "Mr. Stark, I don't feel so good. I don't want to go. I don't want to go, sir. Please. I'm sorry." },
  { id: "movies-15", type: "text", category: "movies", body: "Perfectly balanced, as all things should be." },
  { id: "movies-16", type: "text", category: "movies", body: "Part of the journey is the end." },
  { id: "movies-17", type: "text", category: "movies", body: "And I... am... Iron Man." },
  { id: "movies-18", type: "text", category: "movies", body: "Avengers... assemble." },
  { id: "movies-19", type: "text", category: "movies", body: "I'm a mog: half man, half dog. I'm my own best friend!" },
  { id: "movies-20", type: "text", category: "movies", body: "\"I am your father's brother's nephew's cousin's former roommate.\" \"What's that make us?\" \"Absolutely nothing!\"" },
  { id: "movies-21", type: "text", category: "movies", body: "What's the matter, Colonel Sandurz? Chicken?!" },
  { id: "movies-22", type: "text", category: "movies", body: "There's only one man who would dare give me the raspberry: Lone Starr!" },
  { id: "movies-23", type: "text", category: "movies", body: "\"We were told to comb the desert, so we're combing it!\" \"We ain't found shit!\"" },
  { id: "movies-24", type: "text", category: "movies", body: "\"What happened to then?\" \"We passed then.\" \"When?\" \"Just now.\"" },
  { id: "movies-25", type: "text", category: "movies", body: "In the end, the galaxy will not remember our weapons or our fleets. It will remember whether we chose to stand together when the darkness came." },
  { id: "movies-26", type: "text", category: "movies", body: "This was never about the throne, the crown, or the kingdom. It was about something far greater: the soul of every world that ever dared to dream." },
  { id: "movies-27", type: "text", category: "movies", body: "Together we will harness the storm, forge a new dawn, and unleash a power this universe has never witnessed." },
  { id: "movies-28", type: "text", category: "movies", body: "You ask what makes a hero. I will tell you: not the strength of the arm, but the courage of the heart that refuses to break." },
  { id: "movies-29", type: "text", category: "movies", body: "What began as a simple delivery run became a journey across the stars, and ultimately a reckoning with the very meaning of who we are." },
  { id: "movies-30", type: "text", category: "movies", body: "Victory is not measured in the battles we win, but in the lives we choose to protect along the way." },
  { id: "movies-31", type: "text", category: "movies", body: "I have walked through fire, through shadow, and through the quiet despair that comes when hope itself begins to fade." },
  { id: "movies-32", type: "text", category: "movies", body: "Surrender now, and I may yet allow you to truly, deeply understand the profound mercy of which I am capable." },
  { id: "movies-33", type: "text", category: "movies", body: "Look around you. This is not merely a rebellion. This is the dawn of an age where the oppressed will rise and never again kneel." },
  { id: "movies-34", type: "text", category: "movies", body: "The question is not whether we can win, but whether we are willing to become the kind of people who deserve to." },
  { id: "movies-35", type: "text", category: "movies", body: "Every great empire begins with a single choice, and today, my friends, we choose to delve into legend." },
  { id: "movies-36", type: "text", category: "movies", body: "They told me a machine could never love, never grieve, never truly hope. And yet, here I stand, profoundly and irrevocably alive." },
  { id: "movies-37", type: "text", category: "movies", body: "Heroes are not born in moments of triumph. They are forged in the silent, unseen battles no one will ever know." },
  { id: "movies-38", type: "text", category: "movies", body: "This power was never meant to be controlled. It was meant to be unleashed, and through it, the cosmos itself reborn." },
  { id: "movies-39", type: "text", category: "movies", body: "What is courage, if not fear that has chosen to stand? And what is sacrifice, if not love made visible in its final, fearless act?" },
  { id: "movies-40", type: "text", category: "movies", body: "We did not come here to be remembered. We came here to make sure there was someone left to do the remembering." },
  { id: "movies-41", type: "text", category: "movies", body: "So this is how it ends: not with the roar of cannons, but with the whisper of a promise kept." },
  { id: "movies-42", type: "text", category: "movies", body: "You really thought a force field would stop me? I helped design half the tech in this building. Buddy, I invented the off switch." },
  { id: "movies-43", type: "text", category: "movies", body: "Cut the blue wire. No — the other blue wire, the one tucked behind the red. We've got maybe ten seconds, so please trust me on this." },
  { id: "movies-44", type: "text", category: "movies", body: "I counted three guards on the schematic. On the ground there were six. We're going to need a bigger plan." },
  { id: "movies-45", type: "text", category: "movies", body: "Whatever happens out there, you don't let go of my hand. No matter what you see, no matter what they tell you. Promise me." },
  { id: "movies-46", type: "text", category: "movies", body: "The ship can take the hit; the hull's rated for worse than this. The question is whether we can." },
  { id: "movies-47", type: "text", category: "movies", body: "He's not answering the radio. Either he's gone dark on purpose, or he's just gone. That's either very good or very bad." },
  { id: "movies-48", type: "text", category: "movies", body: "Go now, while there's still a gap in their line. Run. Don't look back. And tell them I was smiling." },
  { id: "genx-1", type: "text", category: "genx", body: "\"Surely you can't be serious.\" \"I am serious. And don't call me Shirley.\"" },
  { id: "genx-2", type: "text", category: "genx", body: "So I've got that going for me, which is nice." },
  { id: "genx-3", type: "text", category: "genx", body: "Back off, man. I'm a scientist." },
  { id: "genx-4", type: "text", category: "genx", body: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it." },
  { id: "genx-5", type: "text", category: "genx", body: "The 1961 Ferrari 250 GT California. Less than a hundred were made." },
  { id: "genx-6", type: "text", category: "genx", body: "My name is Inigo Montoya. You killed my father. Prepare to die." },
  { id: "genx-7", type: "text", category: "genx", body: "You keep using that word. I do not think it means what you think it means." },
  { id: "genx-8", type: "text", category: "genx", body: "What if there is no tomorrow? There wasn't one today." },
  { id: "genx-9", type: "text", category: "genx", body: "We're not worthy! We're not worthy!" },
  { id: "genx-10", type: "text", category: "genx", body: "So you're telling me there's a chance!" },
  { id: "genx-11", type: "text", category: "genx", body: "We hold the world ransom for... one million dollars!" },
  { id: "genx-12", type: "text", category: "genx", body: "Yeah, well, The Dude abides." },
  { id: "genx-13", type: "text", category: "genx", body: "I'm also gonna need you to go ahead and come in on Sunday, too, OK?" },
  { id: "genx-14", type: "text", category: "genx", body: "I want my two dollars!" },
  { id: "genx-15", type: "text", category: "genx", body: "They've got the golden arches. Mine are the golden arcs." },
  { id: "genx-16", type: "text", category: "genx", body: "It's all ball bearings nowadays." },
  { id: "genx-17", type: "text", category: "genx", body: "Nothing to see here. Please disperse!" },
  { id: "genx-18", type: "text", category: "genx", body: "\"Looking good, Billy Ray!\" \"Feeling good, Louis!\"" },
  { id: "genx-19", type: "text", category: "genx", body: "In today's fast-paced academic landscape, one must ask: is skipping school truly wrong, or is it simply a bold reallocation of one's personal time?" },
  { id: "genx-20", type: "text", category: "genx", body: "This isn't merely a golf tournament. It's a chance for one groundskeeper to finally be seen." },
  { id: "genx-21", type: "text", category: "genx", body: "Caddying taught me patience. It taught me humility. And it taught me the value of hard work." },
  { id: "genx-22", type: "text", category: "genx", body: "I'm going to jump this car over the ravine. It's important to note that results may vary and that proper preparation is recommended." },
  { id: "genx-23", type: "text", category: "genx", body: "Before we toilet-paper the principal's house, let's delve into the realm of what could possibly go wrong." },
  { id: "genx-24", type: "text", category: "genx", body: "Some might say the couch does not belong on the roof. Others may argue that it can be, in certain circumstances, an arguably reasonable place for it." },
  { id: "genx-25", type: "text", category: "genx", body: "You asked whether I ate the last slice of pizza. That's a great question. Whether I ate the last slice of pizza is certainly worth examining." },
  { id: "genx-26", type: "text", category: "genx", body: "Whether you're a jock, a nerd, or someone who simply enjoys detention, this Saturday truly has something for everyone." },
  { id: "genx-27", type: "text", category: "genx", body: "So I drove the golf cart into the pond, the cooler floated away, and my boss watched the whole thing. In the end, we all learned something about ourselves that day." },
  { id: "genx-28", type: "text", category: "genx", body: "My uncle's chili was truly spicy. Deeply, profoundly spicy. Everyone at the table was significantly affected." },
  { id: "genx-29", type: "text", category: "genx", body: "High school was a memorable time filled with various experiences, several friends, and a number of teachers who made an impact." },
  { id: "genx-30", type: "text", category: "genx", body: "Excuse me, ghost. I don't wish to be rude, but you are currently inside our refrigerator, and several of us would prefer that you were not." },
  { id: "genx-31", type: "text", category: "genx", body: "I told her the reception was in the backyard. She wore heels. The lawn won." },
  { id: "genx-32", type: "text", category: "genx", body: "Three continents, two weddings, and one buffet I still think about. Not in a good way." },
  { id: "genx-33", type: "text", category: "genx", body: "The sign says the customer is always right. The customer is currently trying to eat the menu." },
  { id: "genx-34", type: "text", category: "genx", body: "I'd like to apologize in advance for what I'm about to say about your haircut." },
  { id: "genx-35", type: "text", category: "genx", body: "You can't be nervous and hungry at the same time. That's science. Eat the shrimp." },
  { id: "millennial-1", type: "text", category: "millennial", body: "Moisture is the essence of wetness, and wetness is the essence of beauty." },
  { id: "millennial-2", type: "text", category: "millennial", body: "The best way to spread Christmas cheer is singing loud for all to hear." },
  { id: "millennial-3", type: "text", category: "millennial", body: "I just like to smile. Smiling's my favorite." },
  { id: "millennial-4", type: "text", category: "millennial", body: "I caught you a delicious bass." },
  { id: "millennial-5", type: "text", category: "millennial", body: "Girls only want boyfriends who have great skills." },
  { id: "millennial-6", type: "text", category: "millennial", body: "On Wednesdays, we wear pink." },
  { id: "millennial-7", type: "text", category: "millennial", body: "Gretchen, stop trying to make \"fetch\" happen. It's not going to happen." },
  { id: "millennial-8", type: "text", category: "millennial", body: "I don't know how to put this, but I'm kind of a big deal." },
  { id: "millennial-9", type: "text", category: "millennial", body: "If you ain't first, you're last." },
  { id: "millennial-10", type: "text", category: "millennial", body: "If you can dodge a wrench, you can dodge a ball." },
  { id: "millennial-11", type: "text", category: "millennial", body: "I'm watching you, Wazowski. Always watching. Always." },
  { id: "millennial-12", type: "text", category: "millennial", body: "Ogres are like onions. Onions have layers. Ogres have layers." },
  { id: "millennial-13", type: "text", category: "millennial", body: "\"Did we just become best friends?\" \"Yep.\"" },
  { id: "millennial-14", type: "text", category: "millennial", body: "No one knows what it means, but it's provocative. It gets the people going." },
  { id: "millennial-15", type: "text", category: "millennial", body: "It's not a man-purse. It's called a satchel. Indiana Jones wears one." },
  { id: "millennial-16", type: "text", category: "millennial", body: "I'm gonna need you to go ahead and come in tomorrow. So if you could be here around nine, that would be great." },
  { id: "millennial-17", type: "text", category: "millennial", body: "You're tacky, and I hate you." },
  { id: "millennial-18", type: "text", category: "millennial", body: "Help me, I'm poor." },
  { id: "millennial-19", type: "text", category: "millennial", body: "This isn't just a chili cook-off. It's a statement about who we are as a family, and I intend to make that statement." },
  { id: "millennial-20", type: "text", category: "millennial", body: "I live by three rules: never quit, never explain, and never wear socks with sandals." },
  { id: "millennial-21", type: "text", category: "millennial", body: "In today's fast-paced backyard environment, we have to ask ourselves whether we are ready for this water balloon fight." },
  { id: "millennial-22", type: "text", category: "millennial", body: "We lost the van, we lost the trophy, and I lost one shoe. But in the end, what we really found out there was each other." },
  { id: "millennial-23", type: "text", category: "millennial", body: "Gary is a deeply unpleasant individual, and I find his behavior profoundly disappointing." },
  { id: "millennial-24", type: "text", category: "millennial", body: "This sheet cake is a testament to what a team can achieve when we leverage our collective strengths." },
  { id: "millennial-25", type: "text", category: "millennial", body: "I'm terribly sorry to interrupt, and I do apologize for the poor timing, but the kitchen is on fire." },
  { id: "millennial-26", type: "text", category: "millennial", body: "You should have seen the party. Something happened, people reacted, and it turned into a memorable experience for everyone involved." },
  { id: "millennial-27", type: "text", category: "millennial", body: "Falling into the pool in a rented tuxedo can often be seen as somewhat embarrassing, and some might say it was arguably my fault." },
  { id: "millennial-28", type: "text", category: "millennial", body: "It's important to note that I did not steal the golf cart. I merely relocated it." },
  { id: "millennial-29", type: "text", category: "millennial", body: "\"Where is the cake?\" \"Where is the cake. That's a great question, and I do want to address it directly.\"" },
  { id: "millennial-30", type: "text", category: "millennial", body: "Whether you're a seasoned boater or a complete beginner, this boat is on fire and we have no paddles." },
  { id: "millennial-31", type: "text", category: "millennial", body: "I'm not mad. I'm just going to go sit in the car for a while with the radio off." },
  { id: "millennial-32", type: "text", category: "millennial", body: "\"You wore a tuxedo to a pool party.\" \"I wore a tuxedo to a pool party, and I stand by it.\"" },
  { id: "millennial-33", type: "text", category: "millennial", body: "He's not my best friend. He's my emergency contact. There's a difference, and I'm not going to explain it." },
  { id: "millennial-34", type: "text", category: "millennial", body: "\"It's a group project, man.\" \"Correct. And I brought a laminated agenda.\"" },
  { id: "millennial-35", type: "text", category: "millennial", body: "I have never lost a bet. I have, on a few occasions, agreed to a different bet about halfway through." },
  { id: "genz-1", type: "text", category: "genz", body: "I only work in black. And sometimes, very, very dark gray." },
  { id: "genz-3", type: "text", category: "genz", body: "All right, let's do this one last time. My name is Peter Parker." },
  { id: "genz-4", type: "text", category: "genz", body: "You won't. It's a leap of faith. That's all it is, Miles." },
  { id: "genz-5", type: "text", category: "genz", body: "Yeah, no, don't put me down for cardio." },
  { id: "genz-6", type: "text", category: "genz", body: "I do hope you keep me in mind for any future game nights." },
  { id: "genz-7", type: "text", category: "genz", body: "\"You guys don't even care about school.\" \"No, we just don't only care about school.\"" },
  { id: "genz-8", type: "text", category: "genz", body: "Maximum effort." },
  { id: "genz-9", type: "text", category: "genz", body: "The only thing I do know is that we have to be kind. Please, be kind, especially when we don't know what's going on." },
  { id: "genz-11", type: "text", category: "genz", body: "Look, we all have a role to play here. You're the brains, he's the muscle, and I'm the one who asks the questions that make everyone uncomfortable — which is also a valuable role, in its own way." },
  { id: "genz-12", type: "text", category: "genz", body: "This is either the best idea we have ever had or the worst idea we have ever had, and honestly, at this point, it is impossible to tell the difference." },
  { id: "genz-13", type: "text", category: "genz", body: "We're a team now. And being a team means trusting each other, believing in each other, and occasionally stealing a van together." },
  { id: "genz-14", type: "text", category: "genz", body: "I have been training my whole life for a moment exactly like this one, and I have to tell you, it is somehow both better and worse than I imagined." },
  { id: "genz-15", type: "text", category: "genz", body: "Guys. Guys. Okay, now that I have everyone's full and undivided attention, I would like to formally propose that we absolutely, positively, one hundred percent do not do that again." },
  { id: "genz-16", type: "text", category: "genz", body: "I want you to know that I am feeling a lot of complicated emotions right now, and I genuinely do not have the vocabulary for most of them." },
  { id: "genz-17", type: "text", category: "genz", body: "And that, my friends, is how you turn a total disaster into a slightly smaller disaster. Teamwork." },
  { id: "genz-18", type: "text", category: "genz", body: "Okay. New plan. Same as the old plan, but this time we run." },
  { id: "genz-19", type: "text", category: "genz", body: "You said you had a plan. You did not say the plan was a shopping cart." },
  { id: "genz-20", type: "text", category: "genz", body: "I'm not scared. My legs are scared. There's a difference and I'd rather not get into it right now." },
  { id: "alpha-1", type: "text", category: "alpha", body: "Rats along his back. When he calls your name, it all fades to black." },
  { id: "alpha-2", type: "text", category: "alpha", body: "But Aunt Lucy said, “If we're kind and polite, the world will be right.”" },
  { id: "alpha-3", type: "text", category: "alpha", body: "He's so fluffy, I'm gonna die!" },
  { id: "alpha-4", type: "text", category: "alpha", body: "And I don't mean it metaphorically or rhetorically or poetically or theoretically or in any other fancy way. I'm Death, straight up." },
  { id: "alpha-5", type: "text", category: "alpha", body: "If you start singing, I'm gonna throw up." },
  { id: "alpha-6", type: "text", category: "alpha", body: "“In today's fast-paced forest landscape, snack security is more important than ever,” announced the squirrel from the top of the picnic table. “Which is why I will now be taking that sandwich.”" },
  { id: "alpha-7", type: "text", category: "alpha", body: "“This isn't just a snowball fight,” said the penguin, adjusting his tiny scarf. “It's a chance to build something bigger than ourselves.”" },
  { id: "alpha-8", type: "text", category: "alpha", body: "“Before we delve into who ate the cake,” said the hamster, “let us take a moment to appreciate the rich tapestry of crumbs on this floor. Truly a testament to a family that eats together.”" },
  { id: "alpha-9", type: "text", category: "alpha", body: "“I have a plan,” said the goat. “It is a bad plan. But it is a plan, and we are fresh out of good ones.”" },
  { id: "alpha-10", type: "text", category: "alpha", body: "“Nobody panic,” said the duck, already panicking. “Panicking is my job. You two just keep flying.”" },
];

export const PUBLIC_BY_ID: Record<string, PublicQuestion> = Object.fromEntries(
  PUBLIC_QUESTIONS.map((q) => [q.id, q]),
);
