import type { PublicQuestion } from "./types";

// PROMPTS ONLY — no answers. Safe to ship to the browser. Generated from
// lib/questions.server.ts by scripts/gen-public-questions.ts — do not edit by hand.
export const PUBLIC_QUESTIONS: PublicQuestion[] = [
  { id: "bbq-1", type: "text", category: "bbq", body: "At long last, it's finally time to get cooking. You've gotten to know your smoker and you've sourced or seasoned the best wood you can possibly find." },
  { id: "bbq-2", type: "text", category: "bbq", body: "Life is too short for bad BBQ!" },
  { id: "bbq-3", type: "text", category: "bbq", body: "I tell people I'm living the dream, because I've turned my hobby into a job." },
  { id: "bbq-4", type: "text", category: "bbq", body: "Didn't have great equipment or great knowledge, but the passion was there. That's never changed." },
  { id: "bbq-5", type: "text", category: "bbq", body: "it's all about cooking delicious food and taking pride in everything we cook" },
  { id: "bbq-6", type: "text", category: "bbq", body: "But the fact that in Texas barbecue, you're taking one of the worst pieces of the animal and converting it into one of the best is a miracle itself." },
  { id: "bbq-7", type: "text", category: "bbq", body: "Sure, I was poor. But barbecue has never been a rich man's pleasure. It's always been a culture of thrift." },
  { id: "bbq-8", type: "text", category: "bbq", body: "I think it's key that you buy the best thing that you can afford." },
  { id: "bbq-9", type: "text", category: "bbq", body: "You learn from your mistakes and you just keep going and trying to do the best you can." },
  { id: "bbq-10", type: "text", category: "bbq", body: "A little beef tallow on the cutting board makes for those sexy slices." },
  { id: "bbq-11", type: "text", category: "bbq", body: "I am an absolute insatiable learner. I love to learn more than anything in the world." },
  { id: "bbq-12", type: "text", category: "bbq", body: "There is a saying in my industry, you buy the meat, not the sauce." },
  { id: "bbq-13", type: "text", category: "bbq", body: "I've always looked at myself as a student of BBQ, because no matter how long you've been doing it, there's always something else to learn." },
  { id: "bbq-14", type: "text", category: "bbq", body: "You can't make a fake fire." },
  { id: "bbq-15", type: "text", category: "bbq", body: "If the temperatures are up and down, it's pretty likely that your firewood is too big, so it's robbing energy from the fire to get to a combustion point." },
  { id: "bbq-16", type: "text", category: "bbq", body: "The worst thing you can do is overcook it." },
  { id: "bbq-17", type: "text", category: "bbq", body: "Like Traeger, I subscribe to the all-natural BBQ philosophy. The hardwood taste and authentic flavors from Traeger's wood fire and wood pellets just can't be beat." },
  { id: "bbq-18", type: "text", category: "bbq", body: "Barbecue feeds your soul because it brings people together." },
  { id: "bbq-19", type: "text", category: "bbq", body: "I do not say I'm lucky. I work too hard to be lucky." },
  { id: "bbq-20", type: "text", category: "bbq", body: "I'd be setting alarms and waking up every 30 minutes; go put a couple logs on the fire, and eventually, it became a business." },
  { id: "bbq-21", type: "text", category: "bbq", body: "In today's world, barbecue is more than just cooking meat over fire. It is a journey that brings people together and nourishes the soul, one tender bite at a time." },
  { id: "bbq-22", type: "text", category: "bbq", body: "Great brisket isn't just about heat; it's about patience, respect, and an unwavering devotion to the craft." },
  { id: "bbq-23", type: "text", category: "bbq", body: "What separates a good pitmaster from a great one? The answer is simple: an unrelenting commitment to the fire." },
  { id: "bbq-24", type: "text", category: "bbq", body: "At the end of the day, smoking meat is about more than flavor. It's about connection, tradition, and the stories we share around the table." },
  { id: "bbq-25", type: "text", category: "bbq", body: "To truly elevate your barbecue, you must learn to harness the smoke and cultivate a deep, profound relationship with your fire." },
  { id: "bbq-26", type: "text", category: "bbq", body: "In a world obsessed with shortcuts, the pitmaster knows the truth: there is no substitute for time, fire, and an enduring love of the craft." },
  { id: "bbq-27", type: "text", category: "bbq", body: "Barbecue is not merely a meal, but a transformative experience that connects us to something far greater than ourselves." },
  { id: "bbq-28", type: "text", category: "bbq", body: "Now more than ever, we must slow down and embrace the low-and-slow philosophy that smoking so beautifully embodies." },
  { id: "bbq-29", type: "text", category: "bbq", body: "At its core, the perfect bark is a testament to patience, precision, and an unwavering pursuit of excellence." },
  { id: "bbq-30", type: "text", category: "bbq", body: "Smoking a brisket is a journey, not a destination. Every hour of fire and patience brings you closer to something truly special." },
  { id: "bbq-31", type: "text", category: "bbq", body: "Remember: a great cook doesn't just feed the body, it feeds the soul and fosters a sense of community that lasts a lifetime." },
  { id: "bbq-32", type: "text", category: "bbq", body: "The grill is more than a tool. It is a teacher, a companion, and a gateway to a richer, more meaningful way of living." },
  { id: "bbq-33", type: "text", category: "bbq", body: "True mastery of the pit requires more than skill. It demands dedication, humility, and a profound respect for the timeless art of fire." },
  { id: "bbq-34", type: "text", category: "bbq", body: "In essence, every great barbecue tells a story, and every story underscores the beauty of slowing down and savoring the moment." },
  { id: "bbq-35", type: "text", category: "bbq", body: "Barbecue teaches us a beautiful lesson: that the best things in life cannot be rushed, only nurtured with care and devotion." },
  { id: "bbq-36", type: "text", category: "bbq", body: "Wrapped it at 165 and let it ride to 203. The bark held, the point jiggled like jelly, and we let it rest a full hour before slicing." },
  { id: "bbq-37", type: "text", category: "bbq", body: "Post oak only on this one. The fire wants tending, not babysitting, and there's a real difference once you learn to feel it." },
  { id: "bbq-38", type: "text", category: "bbq", body: "Spritz every hour with apple cider vinegar, keep the pit steady around 250, and trust the process when the stall hits." },
  { id: "bbq-39", type: "text", category: "bbq", body: "Salt, pepper, smoke. That's the whole recipe, and honestly it's all a good brisket has ever needed." },
  { id: "bbq-40", type: "text", category: "bbq", body: "Got the ribs on before sunrise. By the time the neighbors smelled it, the smoke had already done most of the talking." },
  { id: "business-1", type: "text", category: "business", body: "Discipline equals freedom." },
  { id: "business-2", type: "text", category: "business", body: "It's not what you preach, it's what you tolerate." },
  { id: "business-3", type: "text", category: "business", body: "There are no bad teams, only bad leaders." },
  { id: "business-4", type: "text", category: "business", body: "When setting expectations, no matter what has been said or written, if substandard performance is accepted and no one is held accountable—if there are no consequences—that poor performance becomes the new standard." },
  { id: "business-5", type: "text", category: "business", body: "Good is the enemy of great. And that is one of the key reasons why we have so little that becomes great." },
  { id: "business-6", type: "text", category: "business", body: "Greatness is not a function of circumstance. Greatness, it turns out, is largely a matter of conscious choice, and discipline." },
  { id: "business-7", type: "text", category: "business", body: "Great vision without great people is irrelevant." },
  { id: "business-8", type: "text", category: "business", body: "You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you." },
  { id: "business-9", type: "text", category: "business", body: "Most people do not listen with the intent to understand; they listen with the intent to reply." },
  { id: "business-10", type: "text", category: "business", body: "People don't buy what you do; they buy why you do it." },
  { id: "business-11", type: "text", category: "business", body: "When it comes to standards, as a leader, it's not what you preach, it's what you tolerate." },
  { id: "business-12", type: "text", category: "business", body: "Good is the enemy of great." },
  { id: "business-13", type: "text", category: "business", body: "In today's rapidly evolving marketplace, leadership is not just about giving orders, but about cultivating an environment where every voice can flourish. The leaders who thrive are the ones who learn to listen before they speak." },
  { id: "business-14", type: "text", category: "business", body: "Great teams are built on three things: trust, accountability, and a relentless pursuit of shared purpose. When those align, ordinary people accomplish extraordinary things." },
  { id: "business-15", type: "text", category: "business", body: "What separates good managers from truly great leaders? The answer is simple: great leaders take ownership when things go wrong and give away the credit when things go right." },
  { id: "business-16", type: "text", category: "business", body: "Building a winning culture is a journey, not a destination. Every meeting, every hard conversation, every small act of courage is a step that elevates the entire organization toward something greater." },
  { id: "business-17", type: "text", category: "business", body: "At the end of the day, people don't follow titles, they follow conviction. Remember: the team is always watching how you respond when no one expects you to." },
  { id: "business-18", type: "text", category: "business", body: "In a world where disruption is the only constant, the most valuable skill a leader can possess is the ability to remain calm under pressure. Those who master this will define the next era of business." },
  { id: "business-19", type: "text", category: "business", body: "Now more than ever, organizations must learn to harness change rather than resist it. The companies that endure are not the strongest, but the ones most willing to adapt." },
  { id: "business-20", type: "text", category: "business", body: "Excellence is never an accident. It is the product of discipline, intention, and a deeply held commitment to doing the hard thing when the easy thing is available." },
  { id: "business-21", type: "text", category: "business", body: "At its core, accountability is not about blame, but about ownership. When leaders model this truth, they foster a culture where mistakes become fuel for growth." },
  { id: "business-22", type: "text", category: "business", body: "I used to think the loudest person in the room was the leader. Took me about a decade and one very quiet boss named Diane to figure out that was exactly backwards." },
  { id: "business-23", type: "text", category: "business", body: "Most strategy decks die in the room they were presented in. The ones that survive get repeated by someone who wasn't even there — that's how you know an idea actually landed." },
  { id: "business-24", type: "text", category: "business", body: "Feedback only works when it arrives faster than the next mistake. Wait until the quarterly review and you're not coaching anymore, you're just doing an autopsy." },
  { id: "disney-1", type: "text", category: "disney", body: "You know, in my defense, your poisons all look alike. You might think about re-labeling some of them." },
  { id: "disney-2", type: "text", category: "disney", body: "Or, to save on postage, I'll just poison him with this." },
  { id: "disney-3", type: "text", category: "disney", body: "Memo to me, memo to me: maim you after my meeting." },
  { id: "disney-4", type: "text", category: "disney", body: "Oh, wonderful! Bravo, bravissimo! You ejected that tin-plated buffoon with great panache!" },
  { id: "disney-5", type: "text", category: "disney", body: "Knock it off, Hugo! She's a girl, not a mackerel." },
  { id: "disney-6", type: "text", category: "disney", body: "Can we be real? If my name was Sebastian and I had a cool Jamaican accent, you'd totally help me. You would, you know you would!" },
  { id: "disney-7", type: "text", category: "disney", body: "Genie, wake up and smell the hummus!" },
  { id: "disney-8", type: "text", category: "disney", body: "Let me illuminate to you the precarious situation in which you have found yourself. I am the one they call when things go wrong, and things have indeed gone wrong." },
  { id: "disney-9", type: "text", category: "disney", body: "Earth is a protected wildlife reserve. Yeah, we've been using it to rebuild the mosquito population which, need I remind you, is an endangered species!" },
  { id: "disney-10", type: "text", category: "disney", body: "Don't listen to that guy. He's trying to lead you down the path of righteousness. I'm gonna lead you down the path that rocks." },
  { id: "disney-11", type: "text", category: "disney", body: "In a world where every snowflake falls a little differently, you must remember one thing: the cold never really bothered me. It's not just about letting go, but about embracing who you were always meant to become." },
  { id: "disney-12", type: "text", category: "disney", body: "Cooking is not merely a task, but a profound journey that can nourish the body, delight the senses, and elevate the very soul. Anyone can learn, if only they dare to begin." },
  { id: "disney-13", type: "text", category: "disney", body: "Now more than ever, the ocean calls to those brave enough to listen. At the end of the day, the water connects us all, and the journey beyond the reef will truly change you forever." },
  { id: "disney-14", type: "text", category: "disney", body: "What makes a hero, little one? The answer is simple: a hero is not defined by strength, but by the courage to be kind. That is a truth worth holding close." },
  { id: "disney-15", type: "text", category: "disney", body: "True friendship requires patience, loyalty, and an unwavering commitment to one another through every storm. To infinity, and to the bonds we cultivate along the way." },
  { id: "disney-16", type: "text", category: "disney", body: "To fly, one must first learn to fall, for it is in our most pivotal failures that we discover the transformative power within. Believe, and the impossible becomes merely the next great adventure." },
  { id: "disney-17", type: "text", category: "disney", body: "Family is not just the people who share your name, but the ones who choose to share your dreams. At its core, love is the song that never truly ends." },
  { id: "disney-18", type: "text", category: "disney", body: "The kitchen can be a place to foster confidence, harness creativity, and cultivate a passion that nourishes far more than mere hunger. Greatness, after all, can come from anywhere." },
  { id: "disney-19", type: "text", category: "disney", body: "You've got a friend in me, and that's the kind of thing that doesn't fade just because the seasons turn. Come what may, I'll be right here." },
  { id: "disney-20", type: "text", category: "disney", body: "Adventure is out there, sure as anything, and sometimes it finds you when you least expect it. The trick is keeping your eyes open for it." },
  { id: "speech-1", type: "text", category: "speech", body: "There are these two young fish swimming along and they happen to meet an older fish swimming the other way, who nods at them and says 'Morning, boys. How's the water?' And the two young fish swim on for a bit, and then eventually one of them looks over at the other and goes 'What the hell is water?'" },
  { id: "speech-2", type: "text", category: "speech", body: "The point of the fish story is merely that the most obvious, important realities are often the ones that are hardest to see and talk about." },
  { id: "speech-3", type: "text", category: "speech", body: "With your college diploma you now have a crushing advantage over 8% of the workforce. I'm talking about dropout losers like Bill Gates, Steve Jobs, and Mark Zuckerberg." },
  { id: "speech-4", type: "text", category: "speech", body: "I went from being in the center of the grid to not only off the grid, but underneath the coffee table that the grid sits on, lost in the shag carpeting that is underneath the coffee table supporting the grid." },
  { id: "speech-5", type: "text", category: "speech", body: "If you want to change the world, start off by making your bed." },
  { id: "speech-6", type: "text", category: "speech", body: "If you make your bed every morning you will have accomplished the first task of the day. It will give you a small sense of pride, and it will encourage you to do another task and another and another." },
  { id: "speech-7", type: "text", category: "speech", body: "Death is very likely the single best invention of Life. It is Life's change agent. It clears out the old to make way for the new." },
  { id: "speech-8", type: "text", category: "speech", body: "Stay Hungry. Stay Foolish." },
  { id: "speech-9", type: "text", category: "speech", body: "In today's world, where uncertainty seems to greet us at every turn, you stand ready to write the next chapter of your story. Now more than ever, the future belongs to those brave enough to chase it." },
  { id: "speech-10", type: "text", category: "speech", body: "Your education here was not just about exams and lecture halls, but about becoming the kind of person who lifts others as they climb. That is the truest measure of what you have earned." },
  { id: "speech-11", type: "text", category: "speech", body: "Success out there will demand three things of you: discipline, curiosity, and an unwavering commitment to a purpose larger than yourself. Carry all three and you cannot fail." },
  { id: "speech-12", type: "text", category: "speech", body: "What separates those who merely graduate from those who truly transform the world? The answer is simple: they refuse to let fear write their story. They lean in, and they begin." },
  { id: "speech-13", type: "text", category: "speech", body: "Think of these four years not as a destination but as the first mile of a far greater journey, one that will challenge you to grow in ways you cannot yet imagine. The road ahead is yours to walk." },
  { id: "speech-14", type: "text", category: "speech", body: "As you go forward, I urge you to cultivate resilience, to foster genuine connection, and to harness your talents in service of something profoundly greater than yourselves. These are the habits that elevate a life from ordinary to extraordinary." },
  { id: "speech-15", type: "text", category: "speech", body: "The diploma in your hand tonight is not the finish line you imagined four years ago. It is permission to be a beginner again, which is a far scarier and far better thing." },
  { id: "speech-16", type: "text", category: "speech", body: "Nobody hands you a map for the part that comes next. You learn the terrain by getting a little lost, asking for help, and trying again the next morning." },
];

export const PUBLIC_BY_ID: Record<string, PublicQuestion> = Object.fromEntries(
  PUBLIC_QUESTIONS.map((q) => [q.id, q]),
);
