import "server-only";
import type { FullQuestion } from "./types";

// FULL question bank — answer/reveal/source. SERVER ONLY (the "server-only"
// import fails the build if imported into client code, so answers never ship).
export const FULL_QUESTIONS: FullQuestion[] = [
  {
    id: "bbq-1",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "At long last, it's finally time to get cooking. You've gotten to know your smoker and you've sourced or seasoned the best wood you can possibly find.",
    source:
      'Aaron Franklin & Jordan Mackay, Franklin Barbecue: A Meat-Smoking Manifesto (2015), Chapter 6 "The Cook"',
    reveal:
      'That\'s Aaron Franklin & Jordan Mackay, Franklin Barbecue: A Meat-Smoking Manifesto (2015), Chapter 6 "The Cook".',
  },
  {
    id: "bbq-2",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "Life is too short for bad BBQ!",
    source: 'Danielle "Diva Q" Bennett, Traeger Grills ambassador profile (traeger.com/diva-q)',
    reveal:
      'That\'s Danielle "Diva Q" Bennett, Traeger Grills ambassador profile (traeger.com/diva-q).',
  },
  {
    id: "bbq-3",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "I tell people I'm living the dream, because I've turned my hobby into a job.",
    source:
      "Matt Pittman, Meat Church BBQ — Traeger Collective profile (traeger.com/collective/matt-pittman)",
    reveal:
      "That's Matt Pittman, Meat Church BBQ — Traeger Collective profile (traeger.com/collective/matt-pittman).",
  },
  {
    id: "bbq-5",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "To us, it's all about cooking delicious food and taking pride in everything we cook.",
    source: 'Malcom & Rachelle Reed, "About HowToBBQRight" (2018, since removed from the site)',
    reveal:
      'That\'s Malcom & Rachelle Reed, "About HowToBBQRight" (2018, since removed from the site).',
  },
  {
    id: "bbq-6",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "But the fact that in Texas barbecue, you're taking one of the worst pieces of the animal and converting it into one of the best is a miracle itself.",
    source: "Aaron Franklin, Franklin Barbecue: A Meat-Smoking Manifesto (2015)",
    reveal: "That's Aaron Franklin, Franklin Barbecue: A Meat-Smoking Manifesto (2015).",
  },
  {
    id: "bbq-7",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "Sure, I was poor. But barbecue has never been a rich man's pleasure. It's always been a culture of thrift.",
    source: "Aaron Franklin, Franklin Barbecue: A Meat-Smoking Manifesto (2015)",
    reveal: "That's Aaron Franklin, Franklin Barbecue: A Meat-Smoking Manifesto (2015).",
  },
  {
    id: "bbq-8",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "I think it's key that you buy the best thing that you can afford.",
    source: 'Aaron Franklin, "The Sublime Simplicity of Aaron Franklin," Austin Food Magazine',
    reveal:
      'That\'s Aaron Franklin, "The Sublime Simplicity of Aaron Franklin," Austin Food Magazine.',
  },
  {
    id: "bbq-9",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "You learn from your mistakes and you just keep going and trying to do the best you can.",
    source: "Aaron Franklin, Q&A interview, Austin Food Magazine",
    reveal: "That's Aaron Franklin, Q&A interview, Austin Food Magazine.",
  },
  {
    id: "bbq-10",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "A little beef tallow on the cutting board makes for those sexy slices.",
    source:
      "Matt Pittman (Meat Church BBQ), in \"Going to Texas' Meat Church — Matt Pittman's Barbecue School is a Truly Unique Food Experience,\" PaperCity Magazine",
    reveal:
      "That's Matt Pittman (Meat Church BBQ), in \"Going to Texas' Meat Church — Matt Pittman's Barbecue School is a Truly Unique Food Experience,\" PaperCity Magazine.",
  },
  {
    id: "bbq-11",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "I am an absolute insatiable learner. I love to learn more than anything in the world.",
    source: 'Danielle "Diva Q" Bennett, exclusive interview with Mashed (2021)',
    reveal: 'That\'s Danielle "Diva Q" Bennett, exclusive interview with Mashed (2021).',
  },
  {
    id: "bbq-12",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "There is a saying in my industry, you buy the meat, not the sauce.",
    source: 'Danielle "Diva Q" Bennett, exclusive interview with Mashed (2021)',
    reveal: 'That\'s Danielle "Diva Q" Bennett, exclusive interview with Mashed (2021).',
  },
  {
    id: "bbq-13",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "I've always looked at myself as a student of BBQ, because no matter how long you've been doing it, there's always something else to learn.",
    source: 'Malcom Reed, "About Malcom Reed & HowToBBQRight" (h2qshop.com)',
    reveal: 'That\'s Malcom Reed, "About Malcom Reed & HowToBBQRight" (h2qshop.com).',
  },
  {
    id: "bbq-14",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "You can't make a fake fire.",
    source: "Aaron Franklin, Tasting Table exclusive interview (2023)",
    reveal: "That's Aaron Franklin, Tasting Table exclusive interview (2023).",
  },
  {
    id: "bbq-15",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "If the temperatures are up and down, it's pretty likely that your firewood is too big, so it's robbing energy from the fire to get to a combustion point.",
    source: "Aaron Franklin, Tasting Table exclusive interview (2023)",
    reveal: "That's Aaron Franklin, Tasting Table exclusive interview (2023).",
  },
  {
    id: "bbq-16",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "With steak, the worst thing you can do is overcook it.",
    source: "Aaron Franklin, Tasting Table exclusive interview (2023)",
    reveal: "That's Aaron Franklin, Tasting Table exclusive interview (2023).",
  },
  {
    id: "bbq-17",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "Like Traeger, I subscribe to the all-natural BBQ philosophy. The hardwood taste and authentic flavors from Traeger's wood fire and wood pellets just can't be beat.",
    source:
      'Matt Pittman (Meat Church BBQ), "Traeger Grills Partners with Meat Church BBQ\'s Matt Pittman to Spread the Gospel of Wood-Fired Cooking," PR Newswire (2018)',
    reveal:
      "That's Matt Pittman (Meat Church BBQ), \"Traeger Grills Partners with Meat Church BBQ's Matt Pittman to Spread the Gospel of Wood-Fired Cooking,\" PR Newswire (2018).",
  },
  {
    id: "bbq-18",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "Barbecue feeds your soul because it brings people together.",
    source: 'Danielle "Diva Q" Bennett, Mashed exclusive interview (2021)',
    reveal: 'That\'s Danielle "Diva Q" Bennett, Mashed exclusive interview (2021).',
  },
  {
    id: "bbq-19",
    type: "text",
    category: "bbq",
    answer: "human",
    body: "I do not say I'm lucky. I work too hard to be lucky.",
    source: 'Danielle "Diva Q" Bennett, Mashed exclusive interview on WhistlePig whiskey (2022)',
    reveal:
      'That\'s Danielle "Diva Q" Bennett, Mashed exclusive interview on WhistlePig whiskey (2022).',
  },
  {
    id: "bbq-21",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "Great brisket comes down to three key factors: 1) Preparation — trim the excess fat. 2) Patience — hold a consistent temperature. 3) Rest — allow the meat to relax. Follow these steps for optimal results.",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: "AI — nobody talks in numbered steps.",
  },
  {
    id: "bbq-24",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "Don’t drown good meat in rub until it tastes like a spice cabinet fell down the stairs. Salt, pepper, heat, smoke, and restraint will get you invited back.",
    source: "AI-generated",
    tell: "list-of-three",
    reveal: 'AI — four real ingredients, then "restraint" sneaks onto the list.',
  },
  {
    id: "bbq-35",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "Tinfoil is a crutch, but peach butcher paper is a pitmaster's best friend. It breathes just enough to keep your crust nice and crunchy while holding in those essential juices. Trust the process and don't rush the wrap.",
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: 'AI — "trust the process" is a poster, not a pit.',
  },
  {
    id: "bbq-37",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "In today's world, barbecue is more than just cooking meat over fire. It is a journey that brings people together and nourishes the soul, one tender bite at a time.",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal: 'AI — "In today\'s world," it began, about barbecue.',
  },
  {
    id: "bbq-38",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "Great brisket isn't just about heat; it's about patience, respect, and an unwavering devotion to the craft.",
    source: "AI-generated",
    tell: "list-of-three",
    reveal: 'AI — "patience, respect, and an unwavering devotion" — but no brisket.',
  },
  {
    id: "bbq-40",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "At the end of the day, smoking meat is about more than flavor. It's about connection, tradition, and the stories we share around the table.",
    source: "AI-generated",
    tell: "list-of-three",
    reveal:
      'AI — "connection, tradition, and the stories we share" — three warm words, zero smoke.',
  },
  {
    id: "business-1",
    type: "text",
    category: "business",
    answer: "human",
    body: "Discipline equals freedom.",
    source: "Jocko Willink, Extreme Ownership: How U.S. Navy SEALs Lead and Win (2015)",
    reveal: "That's Jocko Willink, Extreme Ownership: How U.S. Navy SEALs Lead and Win (2015).",
  },
  {
    id: "business-2",
    type: "text",
    category: "business",
    answer: "human",
    body: "It's not what you preach, it's what you tolerate.",
    source:
      "Jocko Willink and Leif Babin, Extreme Ownership: How U.S. Navy SEALs Lead and Win (2015)",
    reveal:
      "That's Jocko Willink and Leif Babin, Extreme Ownership: How U.S. Navy SEALs Lead and Win (2015).",
  },
  {
    id: "business-3",
    type: "text",
    category: "business",
    answer: "human",
    body: "There are no bad teams, only bad leaders.",
    source:
      "Jocko Willink and Leif Babin, Extreme Ownership: How U.S. Navy SEALs Lead and Win (2015)",
    reveal:
      "That's Jocko Willink and Leif Babin, Extreme Ownership: How U.S. Navy SEALs Lead and Win (2015).",
  },
  {
    id: "business-4",
    type: "text",
    category: "business",
    answer: "human",
    body: "When setting expectations, no matter what has been said or written, if substandard performance is accepted and no one is held accountable—if there are no consequences—that poor performance becomes the new standard.",
    source:
      "Jocko Willink and Leif Babin, Extreme Ownership: How U.S. Navy SEALs Lead and Win (2015)",
    reveal:
      "That's Jocko Willink and Leif Babin, Extreme Ownership: How U.S. Navy SEALs Lead and Win (2015).",
  },
  {
    id: "business-5",
    type: "text",
    category: "business",
    answer: "human",
    body: "Good is the enemy of great. And that is one of the key reasons why we have so little that becomes great.",
    source:
      "Jim Collins, Good to Great: Why Some Companies Make the Leap... and Others Don't (2001)",
    reveal:
      "That's Jim Collins, Good to Great: Why Some Companies Make the Leap... and Others Don't (2001).",
  },
  {
    id: "business-6",
    type: "text",
    category: "business",
    answer: "human",
    body: "Greatness is not a function of circumstance. Greatness, it turns out, is largely a matter of conscious choice, and discipline.",
    source:
      "Jim Collins, Good to Great: Why Some Companies Make the Leap... and Others Don't (2001)",
    reveal:
      "That's Jim Collins, Good to Great: Why Some Companies Make the Leap... and Others Don't (2001).",
  },
  {
    id: "business-7",
    type: "text",
    category: "business",
    answer: "human",
    body: "Great vision without great people is irrelevant.",
    source:
      "Jim Collins, Good to Great: Why Some Companies Make the Leap... and Others Don't (2001)",
    reveal:
      "That's Jim Collins, Good to Great: Why Some Companies Make the Leap... and Others Don't (2001).",
  },
  {
    id: "business-8",
    type: "text",
    category: "business",
    answer: "human",
    body: "You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you.",
    source: "Dale Carnegie, How to Win Friends and Influence People (1936)",
    reveal: "That's Dale Carnegie, How to Win Friends and Influence People (1936).",
  },
  {
    id: "business-9",
    type: "text",
    category: "business",
    answer: "human",
    body: "Most people do not listen with the intent to understand; they listen with the intent to reply.",
    source: "Stephen R. Covey, The 7 Habits of Highly Effective People (1989)",
    reveal: "That's Stephen R. Covey, The 7 Habits of Highly Effective People (1989).",
  },
  {
    id: "business-10",
    type: "text",
    category: "business",
    answer: "human",
    body: "People don't buy what you do; they buy why you do it.",
    source: "Simon Sinek, Start with Why: How Great Leaders Inspire Everyone to Take Action (2009)",
    reveal:
      "That's Simon Sinek, Start with Why: How Great Leaders Inspire Everyone to Take Action (2009).",
  },
  {
    id: "business-14",
    type: "text",
    category: "business",
    answer: "bot",
    body: "The market doesn’t care about your legacy strategy or how successful your previous product launch was. Disruption happens when an organization becomes too comfortable protecting past wins instead of cannibalizing its own business model to innovate. Stay paranoid, stay curious, and keep executing.",
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: 'AI — "Stay paranoid, stay curious" is a pep talk where an example should be.',
  },
  {
    id: "business-16",
    type: "text",
    category: "business",
    answer: "bot",
    body: "You're absolutely right, and I apologize for the confusion. That's a great point about retention, and you've clearly thought deeply about this. Building on your excellent observation, psychological safety really is the foundation here.",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: 'AI — "You\'re absolutely right" is a machine folding, not agreeing.',
  },
  {
    id: "business-20",
    type: "text",
    category: "business",
    answer: "bot",
    body: "Your calendar is a confession. It reveals what you reward, what you avoid, and what you are accidentally teaching everyone else to value.",
    source: "AI-generated",
    reveal:
      'Sneaky — "Your calendar is a confession" is a great line, which is exactly why it got you.',
    sneaky: true,
  },
  {
    id: "disney-1",
    type: "text",
    category: "disney",
    answer: "human",
    body: "You have forgotten who you are and so have forgotten me. Look inside yourself, Simba. You are more than what you have become. You must take your place in the Circle of Life.",
    source: "The Lion King (1994) — Mufasa",
    reveal: "That's Mufasa in The Lion King (1994).",
  },
  {
    id: "disney-2",
    type: "text",
    category: "disney",
    answer: "human",
    body: "Everything you see exists together in a delicate balance. As king, you need to understand that balance and respect all the creatures, from the crawling ant to the leaping antelope.",
    source: "The Lion King (1994) — Mufasa",
    reveal: "That's Mufasa in The Lion King (1994).",
  },
  {
    id: "disney-3",
    type: "text",
    category: "disney",
    answer: "human",
    body: "Look, over in that house is a kid who thinks you are the greatest, and it's not because you're a Space Ranger, pal. It's because you're a toy. You are his toy.",
    source: "Toy Story (1995) — Woody",
    reveal: "That's Woody in Toy Story (1995).",
  },
  {
    id: "disney-4",
    type: "text",
    category: "disney",
    answer: "human",
    body: "You are a sad, strange little man, and you have my pity. Farewell.",
    source: "Toy Story (1995) — Buzz Lightyear",
    reveal: "That's Buzz Lightyear in Toy Story (1995).",
  },
  {
    id: "disney-5",
    type: "text",
    category: "disney",
    answer: "human",
    body: "Well, you can't never let anything happen to him. Then nothing would ever happen to him. Not much fun for little Harpo.",
    source: "Finding Nemo (2003) — Dory",
    reveal: "That's Dory in Finding Nemo (2003).",
  },
  {
    id: "disney-6",
    type: "text",
    category: "disney",
    answer: "human",
    body: "If he could learn to love another and earn her love in return by the time the last petal fell, then the spell would be broken. If not, he would be doomed to remain a beast for all time.",
    source: "Beauty and the Beast (1991) — prologue narration",
    reveal: "That's prologue narration in Beauty and the Beast (1991).",
  },
  {
    id: "disney-7",
    type: "text",
    category: "disney",
    answer: "human",
    body: "Dishonor! Dishonor on your whole family! Make a note of this: dishonor on you, dishonor on your cow!",
    source: "Mulan (1998) — Mushu",
    reveal: "That's Mushu in Mulan (1998).",
  },
  {
    id: "disney-8",
    type: "text",
    category: "disney",
    answer: "human",
    body: "The flower that blooms in adversity is the most rare and beautiful of all. You don't meet a girl like that every dynasty.",
    source: "Mulan (1998) — The Emperor",
    reveal: "That's The Emperor in Mulan (1998).",
  },
  {
    id: "disney-9",
    type: "text",
    category: "disney",
    answer: "human",
    body: "Some people are worth melting for. Just maybe not right this second.",
    source: "Frozen (2013) — Olaf",
    reveal: "That's Olaf in Frozen (2013).",
  },
  {
    id: "disney-10",
    type: "text",
    category: "disney",
    answer: "human",
    body: "Not everyone can become a great artist, but a great artist can come from anywhere. It is difficult to imagine more humble origins than those of the genius now cooking at Gusteau's.",
    source: "Ratatouille (2007) — Anton Ego",
    reveal: "That's Anton Ego in Ratatouille (2007).",
  },
  {
    id: "disney-11",
    type: "text",
    category: "disney",
    answer: "human",
    body: "You made it! Go! Go save Riley! Take her to the moon for me… okay?",
    source: "Inside Out (2015) — Bing Bong",
    reveal: "That's Bing Bong in Inside Out (2015).",
  },
  {
    id: "disney-12",
    type: "text",
    category: "disney",
    answer: "human",
    body: "It's kind of fun to do the impossible.",
    source: "Walt Disney",
    reveal: "That's Walt Disney.",
  },
  {
    id: "disney-18",
    type: "text",
    category: "disney",
    answer: "bot",
    body: "Hurrying won't make the winter pass any faster, my little friend, as every single snowflake has its own special time to dance. Sit here by the hearth with me and let the frost paint its pictures on the windowpanes. Spring always knows exactly when to arrive.",
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: 'AI — "Spring always knows exactly when to arrive" comes straight off a greeting card.',
  },
  {
    id: "speech-1",
    type: "text",
    category: "speech",
    answer: "human",
    body: "There are these two young fish swimming along and they happen to meet an older fish swimming the other way, who nods at them and says 'Morning, boys. How's the water?' And the two young fish swim on for a bit, and then eventually one of them looks over at the other and goes 'What the hell is water?'",
    source: 'David Foster Wallace, "This Is Water" commencement address, Kenyon College, 2005',
    reveal:
      'That\'s David Foster Wallace, "This Is Water" commencement address, Kenyon College, 2005.',
  },
  {
    id: "speech-2",
    type: "text",
    category: "speech",
    answer: "human",
    body: "The point of the fish story is merely that the most obvious, important realities are often the ones that are hardest to see and talk about.",
    source: 'David Foster Wallace, "This Is Water" commencement address, Kenyon College (2005)',
    reveal:
      'That\'s David Foster Wallace, "This Is Water" commencement address, Kenyon College (2005).',
  },
  {
    id: "speech-3",
    type: "text",
    category: "speech",
    answer: "human",
    body: "With your college diploma you now have a crushing advantage over 8% of the workforce. I'm talking about dropout losers like Bill Gates, Steve Jobs, and Mark Zuckerberg.",
    source: "Conan O'Brien, commencement address, Dartmouth College (2011)",
    reveal: "That's Conan O'Brien, commencement address, Dartmouth College (2011).",
  },
  {
    id: "speech-4",
    type: "text",
    category: "speech",
    answer: "human",
    body: "I went from being in the center of the grid to not only off the grid, but underneath the coffee table that the grid sits on, lost in the shag carpeting that is underneath the coffee table supporting the grid.",
    source: "Conan O'Brien, Dartmouth College Commencement Address (2011)",
    reveal: "That's Conan O'Brien, Dartmouth College Commencement Address (2011).",
  },
  {
    id: "speech-5",
    type: "text",
    category: "speech",
    answer: "human",
    body: "And, if by chance you have a miserable day, you will come home to a bed that is made — that you made — and a made bed gives you encouragement that tomorrow will be better. If you want to change the world, start off by making your bed.",
    source: "Admiral William H. McRaven, 2014 Commencement Address, University of Texas at Austin",
    reveal:
      "That's Admiral William H. McRaven, 2014 Commencement Address, University of Texas at Austin.",
  },
  {
    id: "speech-6",
    type: "text",
    category: "speech",
    answer: "human",
    body: "If you make your bed every morning you will have accomplished the first task of the day. It will give you a small sense of pride, and it will encourage you to do another task and another and another.",
    source:
      "Admiral William H. McRaven, commencement address, University of Texas at Austin (May 17, 2014)",
    reveal:
      "That's Admiral William H. McRaven, commencement address, University of Texas at Austin (May 17, 2014).",
  },
  {
    id: "speech-7",
    type: "text",
    category: "speech",
    answer: "human",
    body: "Death is very likely the single best invention of Life. It is Life's change agent. It clears out the old to make way for the new.",
    source: "Steve Jobs, Commencement Address, Stanford University (2005)",
    reveal: "That's Steve Jobs, Commencement Address, Stanford University (2005).",
  },
  {
    id: "speech-8",
    type: "text",
    category: "speech",
    answer: "human",
    body: "And I have always wished that for myself. And now, as you graduate to begin anew, I wish that for you. Stay Hungry. Stay Foolish.",
    source: "Steve Jobs, Commencement Address, Stanford University (June 12, 2005)",
    reveal: "That's Steve Jobs, Commencement Address, Stanford University (June 12, 2005).",
  },
  {
    id: "speech-12",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "Do not let the fear of making a mistake paralyze your ambition, because every failure is simply a tuition payment toward your future wisdom. The most extraordinary lives are rarely linear; they are messy, unpredictable, and defined by the moments someone chose to get back up. Write a story worth telling.",
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: 'AI — it demanded "a story worth telling" without telling one.',
  },
  {
    id: "movies-1",
    type: "text",
    category: "movies",
    answer: "human",
    body: "This is our most desperate hour. Help me, Obi-Wan Kenobi. You're my only hope.",
    source: "Star Wars: A New Hope (1977) — Princess Leia",
    reveal: "That's Princess Leia in Star Wars: A New Hope (1977).",
  },
  {
    id: "movies-2",
    type: "text",
    category: "movies",
    answer: "human",
    body: "That's no moon. It's a space station.",
    source: "Star Wars: A New Hope (1977) — Obi-Wan Kenobi",
    reveal: "That's Obi-Wan Kenobi in Star Wars: A New Hope (1977).",
  },
  {
    id: "movies-3",
    type: "text",
    category: "movies",
    answer: "human",
    body: "I find your lack of faith disturbing.",
    source: "Star Wars: A New Hope (1977) — Darth Vader",
    reveal: "That's Darth Vader in Star Wars: A New Hope (1977).",
  },
  {
    id: "movies-4",
    type: "text",
    category: "movies",
    answer: "human",
    body: "These aren't the droids you're looking for.",
    source: "Star Wars: A New Hope (1977) — Obi-Wan Kenobi",
    reveal: "That's Obi-Wan Kenobi in Star Wars: A New Hope (1977).",
  },
  {
    id: "movies-5",
    type: "text",
    category: "movies",
    answer: "human",
    body: "No! Try not. Do... or do not. There is no try.",
    source: "The Empire Strikes Back (1980) — Yoda",
    reveal: "That's Yoda in The Empire Strikes Back (1980).",
  },
  {
    id: "movies-6",
    type: "text",
    category: "movies",
    answer: "human",
    body: "No. I am your father.",
    source: "The Empire Strikes Back (1980) — Darth Vader",
    reveal: "That's Darth Vader in The Empire Strikes Back (1980).",
  },
  {
    id: "movies-7",
    type: "text",
    category: "movies",
    answer: "human",
    body: "Never tell me the odds!",
    source: "The Empire Strikes Back (1980) — Han Solo",
    reveal: "That's Han Solo in The Empire Strikes Back (1980).",
  },
  {
    id: "movies-8",
    type: "text",
    category: "movies",
    answer: "human",
    body: '"I love you." "I know."',
    source: "The Empire Strikes Back (1980) — Leia & Han Solo",
    reveal: "That's Leia & Han Solo in The Empire Strikes Back (1980).",
  },
  {
    id: "movies-9",
    type: "text",
    category: "movies",
    answer: "human",
    body: "Hello there.",
    source: "Star Wars: Revenge of the Sith (2005) — Obi-Wan Kenobi",
    reveal: "That's Obi-Wan Kenobi in Star Wars: Revenge of the Sith (2005).",
  },
  {
    id: "movies-10",
    type: "text",
    category: "movies",
    answer: "human",
    body: "Genius, billionaire, playboy, philanthropist.",
    source: "The Avengers (2012) — Tony Stark",
    reveal: "That's Tony Stark in The Avengers (2012).",
  },
  {
    id: "movies-11",
    type: "text",
    category: "movies",
    answer: "human",
    body: "That's my secret, Cap. I'm always angry.",
    source: "The Avengers (2012) — Bruce Banner",
    reveal: "That's Bruce Banner in The Avengers (2012).",
  },
  {
    id: "movies-12",
    type: "text",
    category: "movies",
    answer: "human",
    body: "Puny god.",
    source: "The Avengers (2012) — Hulk",
    reveal: "That's Hulk in The Avengers (2012).",
  },
  {
    id: "movies-13",
    type: "text",
    category: "movies",
    answer: "human",
    body: "Even when I had nothing, I had Bucky.",
    source: "Captain America: The Winter Soldier (2014) — Steve Rogers",
    reveal: "That's Steve Rogers in Captain America: The Winter Soldier (2014).",
  },
  {
    id: "movies-14",
    type: "text",
    category: "movies",
    answer: "human",
    body: "Mr. Stark, I don't feel so good. I don't want to go. I don't want to go, sir. Please. I'm sorry.",
    source: "Avengers: Infinity War (2018) — Peter Parker",
    reveal: "That's Peter Parker in Avengers: Infinity War (2018).",
  },
  {
    id: "movies-15",
    type: "text",
    category: "movies",
    answer: "human",
    body: "Perfectly balanced, as all things should be.",
    source: "Avengers: Infinity War (2018) — Thanos",
    reveal: "That's Thanos in Avengers: Infinity War (2018).",
  },
  {
    id: "movies-16",
    type: "text",
    category: "movies",
    answer: "human",
    body: "Part of the journey is the end.",
    source: "Avengers: Endgame (2019) — Tony Stark",
    reveal: "That's Tony Stark in Avengers: Endgame (2019).",
  },
  {
    id: "movies-17",
    type: "text",
    category: "movies",
    answer: "human",
    body: "And I... am... Iron Man.",
    source: "Avengers: Endgame (2019) — Tony Stark",
    reveal: "That's Tony Stark in Avengers: Endgame (2019).",
  },
  {
    id: "movies-18",
    type: "text",
    category: "movies",
    answer: "human",
    body: "Avengers... assemble.",
    source: "Avengers: Endgame (2019) — Steve Rogers",
    reveal: "That's Steve Rogers in Avengers: Endgame (2019).",
  },
  {
    id: "movies-19",
    type: "text",
    category: "movies",
    answer: "human",
    body: "I'm a mog: half man, half dog. I'm my own best friend!",
    source: "Spaceballs (1987) — Barf",
    reveal: "That's Barf in Spaceballs (1987).",
  },
  {
    id: "movies-20",
    type: "text",
    category: "movies",
    answer: "human",
    body: '"I am your father\'s brother\'s nephew\'s cousin\'s former roommate." "What\'s that make us?" "Absolutely nothing!"',
    source: "Spaceballs (1987) — Dark Helmet & Lone Starr",
    reveal: "That's Dark Helmet & Lone Starr in Spaceballs (1987).",
  },
  {
    id: "movies-21",
    type: "text",
    category: "movies",
    answer: "human",
    body: "What's the matter, Colonel Sandurz? Chicken?!",
    source: "Spaceballs (1987) — Dark Helmet",
    reveal: "That's Dark Helmet in Spaceballs (1987).",
  },
  {
    id: "movies-22",
    type: "text",
    category: "movies",
    answer: "human",
    body: "There's only one man who would dare give me the raspberry: Lone Starr!",
    source: "Spaceballs (1987) — Dark Helmet",
    reveal: "That's Dark Helmet in Spaceballs (1987).",
  },
  {
    id: "movies-23",
    type: "text",
    category: "movies",
    answer: "human",
    body: '"We were told to comb the desert, so we\'re combing it!" "We ain\'t found shit!"',
    source: "Spaceballs (1987) — Dark Helmet & a trooper",
    reveal: "That's Dark Helmet & a trooper in Spaceballs (1987).",
  },
  {
    id: "movies-24",
    type: "text",
    category: "movies",
    answer: "human",
    body: '"What happened to then?" "We passed then." "When?" "Just now."',
    source: "Spaceballs (1987) — Dark Helmet & Colonel Sandurz",
    reveal: "That's Dark Helmet & Colonel Sandurz in Spaceballs (1987).",
  },
  {
    id: "movies-26",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "This was never about the throne, the crown, or the kingdom. It was about something far greater: the soul of every world that ever dared to dream.",
    source: "AI-generated",
    tell: "not-just-x",
    reveal: 'AI — everything traded up to "the soul of every world" — it was about the throne.',
  },
  {
    id: "movies-27",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "Together we will harness the storm, forge a new dawn, and unleash a power this universe has never witnessed.",
    source: "AI-generated",
    tell: "list-of-three",
    reveal: "AI — three verbs, each grander and vaguer than the last.",
  },
  {
    id: "movies-30",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "Victory is not measured in the battles we win, but in the lives we choose to protect along the way.",
    source: "AI-generated",
    tell: "not-just-x",
    reveal:
      'AI — the "not measured in X, but in Y" flip; victory is famously measured in battles you win.',
  },
  {
    id: "movies-32",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "Surrender now, and I may yet allow you to truly, deeply understand the profound mercy of which I am capable.",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: "AI — the villain turned the volume up instead of making a threat.",
  },
  {
    id: "movies-35",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "Every great empire begins with a single choice, and today, my friends, we choose to delve into legend.",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: 'AI — armies charge; chatbots "delve into legend."',
  },
  {
    id: "movies-36",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "They told me a machine could never love, never grieve, never truly hope. And yet, here I stand, profoundly and irrevocably alive.",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: 'AI — "profoundly and irrevocably alive," said no living thing ever.',
  },
  {
    id: "genx-1",
    type: "text",
    category: "genx",
    answer: "human",
    body: '"Surely you can\'t be serious." "I am serious. And don\'t call me Shirley."',
    source: "Airplane! (1980) — Ted Striker & Dr. Rumack",
    reveal: "That's Ted Striker & Dr. Rumack in Airplane! (1980).",
  },
  {
    id: "genx-2",
    type: "text",
    category: "genx",
    answer: "human",
    body: "So I've got that going for me, which is nice.",
    source: "Caddyshack (1980) — Carl Spackler",
    reveal: "That's Carl Spackler in Caddyshack (1980).",
  },
  {
    id: "genx-3",
    type: "text",
    category: "genx",
    answer: "human",
    body: "Back off, man. I'm a scientist.",
    source: "Ghostbusters (1984) — Dr. Peter Venkman",
    reveal: "That's Dr. Peter Venkman in Ghostbusters (1984).",
  },
  {
    id: "genx-4",
    type: "text",
    category: "genx",
    answer: "human",
    body: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.",
    source: "Ferris Bueller's Day Off (1986) — Ferris Bueller",
    reveal: "That's Ferris Bueller in Ferris Bueller's Day Off (1986).",
  },
  {
    id: "genx-5",
    type: "text",
    category: "genx",
    answer: "human",
    body: "The 1961 Ferrari 250 GT California. Less than a hundred were made.",
    source: "Ferris Bueller's Day Off (1986) — Cameron Frye",
    reveal: "That's Cameron Frye in Ferris Bueller's Day Off (1986).",
  },
  {
    id: "genx-6",
    type: "text",
    category: "genx",
    answer: "human",
    body: "My name is Inigo Montoya. You killed my father. Prepare to die.",
    source: "The Princess Bride (1987) — Inigo Montoya",
    reveal: "That's Inigo Montoya in The Princess Bride (1987).",
  },
  {
    id: "genx-7",
    type: "text",
    category: "genx",
    answer: "human",
    body: "You keep using that word. I do not think it means what you think it means.",
    source: "The Princess Bride (1987) — Inigo Montoya",
    reveal: "That's Inigo Montoya in The Princess Bride (1987).",
  },
  {
    id: "genx-8",
    type: "text",
    category: "genx",
    answer: "human",
    body: "What if there is no tomorrow? There wasn't one today.",
    source: "Groundhog Day (1993) — Phil Connors",
    reveal: "That's Phil Connors in Groundhog Day (1993).",
  },
  {
    id: "genx-9",
    type: "text",
    category: "genx",
    answer: "human",
    body: "We're not worthy! We're not worthy!",
    source: "Wayne's World (1992) — Wayne & Garth",
    reveal: "That's Wayne & Garth in Wayne's World (1992).",
  },
  {
    id: "genx-10",
    type: "text",
    category: "genx",
    answer: "human",
    body: "So you're telling me there's a chance!",
    source: "Dumb and Dumber (1994) — Lloyd Christmas",
    reveal: "That's Lloyd Christmas in Dumb and Dumber (1994).",
  },
  {
    id: "genx-11",
    type: "text",
    category: "genx",
    answer: "human",
    body: "We get the warhead and hold the world ransom for... one million dollars!",
    source: "Austin Powers: International Man of Mystery (1997) — Dr. Evil",
    reveal: "That's Dr. Evil in Austin Powers: International Man of Mystery (1997).",
  },
  {
    id: "genx-12",
    type: "text",
    category: "genx",
    answer: "human",
    body: "Yeah, well, The Dude abides.",
    source: "The Big Lebowski (1998) — The Dude",
    reveal: "That's The Dude in The Big Lebowski (1998).",
  },
  {
    id: "genx-13",
    type: "text",
    category: "genx",
    answer: "human",
    body: "I'm also gonna need you to go ahead and come in on Sunday, too, OK?",
    source: "Office Space (1999) — Bill Lumbergh",
    reveal: "That's Bill Lumbergh in Office Space (1999).",
  },
  {
    id: "genx-14",
    type: "text",
    category: "genx",
    answer: "human",
    body: "I want my two dollars!",
    source: "Better Off Dead (1985) — Johnny the paperboy",
    reveal: "That's Johnny the paperboy in Better Off Dead (1985).",
  },
  {
    id: "genx-15",
    type: "text",
    category: "genx",
    answer: "human",
    body: "They've got the golden arches. Mine are the golden arcs.",
    source: "Coming to America (1988) — Cleo McDowell",
    reveal: "That's Cleo McDowell in Coming to America (1988).",
  },
  {
    id: "genx-16",
    type: "text",
    category: "genx",
    answer: "human",
    body: "It's all ball bearings nowadays.",
    source: "Fletch (1985) — Fletch",
    reveal: "That's Fletch in Fletch (1985).",
  },
  {
    id: "genx-17",
    type: "text",
    category: "genx",
    answer: "human",
    body: "Nothing to see here. Please disperse!",
    source: "The Naked Gun (1988) — Lt. Frank Drebin",
    reveal: "That's Lt. Frank Drebin in The Naked Gun (1988).",
  },
  {
    id: "genx-18",
    type: "text",
    category: "genx",
    answer: "human",
    body: '"Looking good, Billy Ray!" "Feeling good, Louis!"',
    source: "Trading Places (1983) — Louis Winthorpe III & Billy Ray Valentine",
    reveal: "That's Louis Winthorpe III & Billy Ray Valentine in Trading Places (1983).",
  },
  {
    id: "genx-19",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "In today's fast-paced academic landscape, one must ask: is skipping school truly wrong, or is it simply a bold reallocation of one's personal time?",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal: 'AI — no kid ever ditched school in a "fast-paced academic landscape."',
  },
  {
    id: "genx-20",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "This isn't merely a golf tournament. It's a chance for one groundskeeper to finally be seen.",
    source: "AI-generated",
    tell: "not-just-x",
    reveal: "AI — the old \"isn't merely X, it's Y\" upgrade — it's a golf tournament.",
  },
  {
    id: "genx-21",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "Caddying taught me patience. It taught me humility. And it taught me the value of hard work.",
    source: "AI-generated",
    tell: "list-of-three",
    reveal: "AI — three lessons, suspiciously equal in size.",
  },
  {
    id: "genx-23",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "Before we toilet-paper the principal's house, let's delve into the realm of what could possibly go wrong.",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: 'AI — teenagers do not "delve into the realm" of anything.',
  },
  {
    id: "genx-25",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "You asked whether I ate the last slice of pizza. That's a great question. Whether I ate the last slice of pizza is certainly worth examining.",
    source: "AI-generated",
    tell: "restates-question",
    reveal: "AI — it complimented the pizza question twice and never answered it.",
  },
  {
    id: "genx-27",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "So I drove the golf cart into the pond, the cooler floated away, and my boss watched the whole thing. In the end, we all learned something about ourselves that day.",
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: "AI — the golf cart sank; the life lesson was pushed in after it.",
  },
  {
    id: "genx-28",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "My uncle's chili was truly spicy. Deeply, profoundly spicy. Everyone at the table was significantly affected.",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: "AI — truly, deeply, profoundly... one actual detail would have done it.",
  },
  {
    id: "genx-30",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "Excuse me, ghost. I don't wish to be rude, but you are currently inside our refrigerator, and several of us would prefer that you were not.",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: "AI — customer-service manners, ghost customer.",
  },
  {
    id: "genx-35",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "You can't be nervous and hungry at the same time. That's science. Eat the shrimp.",
    source: "AI-generated",
    reveal: 'Sneaky — "That\'s science. Eat the shrimp." would have gotten us too.',
    sneaky: true,
  },
  {
    id: "millennial-1",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "Moisture is the essence of wetness, and wetness is the essence of beauty.",
    source: "Zoolander (2001) — Derek Zoolander",
    reveal: "That's Derek Zoolander in Zoolander (2001).",
  },
  {
    id: "millennial-2",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "The best way to spread Christmas cheer is singing loud for all to hear.",
    source: "Elf (2003) — Buddy",
    reveal: "That's Buddy in Elf (2003).",
  },
  {
    id: "millennial-3",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "I just like to smile. Smiling's my favorite.",
    source: "Elf (2003) — Buddy",
    reveal: "That's Buddy in Elf (2003).",
  },
  {
    id: "millennial-4",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "I caught you a delicious bass.",
    source: "Napoleon Dynamite (2004) — Napoleon",
    reveal: "That's Napoleon in Napoleon Dynamite (2004).",
  },
  {
    id: "millennial-5",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "Girls only want boyfriends who have great skills.",
    source: "Napoleon Dynamite (2004) — Napoleon",
    reveal: "That's Napoleon in Napoleon Dynamite (2004).",
  },
  {
    id: "millennial-6",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "On Wednesdays, we wear pink.",
    source: "Mean Girls (2004) — Karen Smith",
    reveal: "That's Karen Smith in Mean Girls (2004).",
  },
  {
    id: "millennial-7",
    type: "text",
    category: "millennial",
    answer: "human",
    body: 'Gretchen, stop trying to make "fetch" happen. It\'s not going to happen.',
    source: "Mean Girls (2004) — Regina George",
    reveal: "That's Regina George in Mean Girls (2004).",
  },
  {
    id: "millennial-8",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "I don't know how to put this, but I'm kind of a big deal.",
    source: "Anchorman: The Legend of Ron Burgundy (2004) — Ron Burgundy",
    reveal: "That's Ron Burgundy in Anchorman: The Legend of Ron Burgundy (2004).",
  },
  {
    id: "millennial-9",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "If you ain't first, you're last.",
    source: "Talladega Nights: The Ballad of Ricky Bobby (2006) — Reese Bobby",
    reveal: "That's Reese Bobby in Talladega Nights: The Ballad of Ricky Bobby (2006).",
  },
  {
    id: "millennial-10",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "If you can dodge a wrench, you can dodge a ball.",
    source: "DodgeBall: A True Underdog Story (2004) — Patches O'Houlihan",
    reveal: "That's Patches O'Houlihan in DodgeBall: A True Underdog Story (2004).",
  },
  {
    id: "millennial-11",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "I'm watching you, Wazowski. Always watching. Always.",
    source: "Monsters, Inc. (2001) — Roz",
    reveal: "That's Roz in Monsters, Inc. (2001).",
  },
  {
    id: "millennial-12",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "Ogres are like onions. Onions have layers. Ogres have layers.",
    source: "Shrek (2001) — Shrek",
    reveal: "That's Shrek in Shrek (2001).",
  },
  {
    id: "millennial-13",
    type: "text",
    category: "millennial",
    answer: "human",
    body: '"Did we just become best friends?" "Yep."',
    source: "Step Brothers (2008) — Brennan & Dale",
    reveal: "That's Brennan & Dale in Step Brothers (2008).",
  },
  {
    id: "millennial-14",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "No one knows what it means, but it's provocative. It gets the people going.",
    source: "Blades of Glory (2007) — Chazz Michael Michaels",
    reveal: "That's Chazz Michael Michaels in Blades of Glory (2007).",
  },
  {
    id: "millennial-15",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "It's not a man-purse. It's called a satchel. Indiana Jones wears one.",
    source: "The Hangover (2009) — Alan",
    reveal: "That's Alan in The Hangover (2009).",
  },
  {
    id: "millennial-16",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "I'm gonna need you to go ahead and come in tomorrow. So if you could be here around nine, that would be great.",
    source: "Office Space (1999) — Bill Lumbergh",
    reveal: "That's Bill Lumbergh in Office Space (1999).",
  },
  {
    id: "millennial-17",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "You're tacky, and I hate you.",
    source: "School of Rock (2003) — Billy",
    reveal: "That's Billy in School of Rock (2003).",
  },
  {
    id: "millennial-18",
    type: "text",
    category: "millennial",
    answer: "human",
    body: "Help me, I'm poor.",
    source: "Bridesmaids (2011) — Annie",
    reveal: "That's Annie in Bridesmaids (2011).",
  },
  {
    id: "millennial-19",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "This isn't just a chili cook-off. It's a statement about who we are as a family, and I intend to make that statement.",
    source: "AI-generated",
    tell: "not-just-x",
    reveal: "AI — \"isn't just X, it's Y\" strikes again; it is, in fact, a chili cook-off.",
  },
  {
    id: "millennial-20",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "I live by three rules: never quit, never explain, and never wear socks with sandals.",
    source: "AI-generated",
    tell: "list-of-three",
    reveal: "AI — a list so tidy it was measured with a ruler.",
  },
  {
    id: "millennial-21",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "In today's fast-paced backyard environment, we have to ask ourselves whether we are ready for this water balloon fight.",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal: "AI — it cleared its throat for a water balloon fight.",
  },
  {
    id: "millennial-22",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "We lost the van, we lost the trophy, and I lost one shoe. But in the end, what we really found out there was each other.",
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: "AI — the gag ended at the shoe; the moral was stapled on.",
  },
  {
    id: "millennial-23",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "Gary is a deeply unpleasant individual, and I find his behavior profoundly disappointing.",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: 'AI — "deeply" and "profoundly" doing the work of one actual fact about Gary.',
  },
  {
    id: "millennial-24",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "This sheet cake is a testament to what a team can achieve when we leverage our collective strengths.",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: 'AI — it\'s a sheet cake, not "a testament to" anything.',
  },
  {
    id: "millennial-25",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "I'm terribly sorry to interrupt, and I do apologize for the poor timing, but the kitchen is on fire.",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: "AI — two apologies before mentioning the fire.",
  },
  {
    id: "millennial-29",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: '"Where is the cake?" "Where is the cake. That\'s a great question, and I do want to address it directly."',
    source: "AI-generated",
    tell: "restates-question",
    reveal: "AI — echoing your question back is a stall, and the cake is still missing.",
  },
  {
    id: "millennial-31",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "I'm not mad. I'm just going to go sit in the car for a while with the radio off.",
    source: "AI-generated",
    reveal: "Sneaky — the radio being off is the kind of detail that used to be safely human.",
    sneaky: true,
  },
  {
    id: "millennial-32",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: '"You wore a tuxedo to a pool party." "I wore a tuxedo to a pool party, and I stand by it."',
    source: "AI-generated",
    reveal:
      "Sneaky — repeating the accusation word for word is a real comedy move; the bot borrowed it cleanly.",
    sneaky: true,
  },
  {
    id: "millennial-33",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "He's not my best friend. He's my emergency contact. There's a difference, and I'm not going to explain it.",
    source: "AI-generated",
    reveal: "Sneaky — this one fools entire rooms; even money at best.",
    sneaky: true,
  },
  {
    id: "millennial-34",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: '"It\'s a group project, man." "Correct. And I brought a laminated agenda."',
    source: "AI-generated",
    reveal: "Sneaky — the laminated agenda got you, and it got everybody.",
    sneaky: true,
  },
  {
    id: "millennial-35",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "I have never lost a bet. I have, on a few occasions, agreed to a different bet about halfway through.",
    source: "AI-generated",
    reveal: "Sneaky — weaseling out of what counts as a bet is a genuinely good joke.",
    sneaky: true,
  },
  {
    id: "genz-1",
    type: "text",
    category: "genz",
    answer: "human",
    body: "I only work in black. And sometimes, very, very dark gray.",
    source: "The Lego Movie (2014) — Batman",
    reveal: "That's Batman in The Lego Movie (2014).",
  },
  {
    id: "genz-3",
    type: "text",
    category: "genz",
    answer: "human",
    body: "All right, let's do this one last time. My name is Peter Parker.",
    source: "Spider-Man: Into the Spider-Verse (2018) — Peter Parker",
    reveal: "That's Peter Parker in Spider-Man: Into the Spider-Verse (2018).",
  },
  {
    id: "genz-4",
    type: "text",
    category: "genz",
    answer: "human",
    body: "You won't. It's a leap of faith. That's all it is, Miles.",
    source: "Spider-Man: Into the Spider-Verse (2018) — Peter B. Parker",
    reveal: "That's Peter B. Parker in Spider-Man: Into the Spider-Verse (2018).",
  },
  {
    id: "genz-5",
    type: "text",
    category: "genz",
    answer: "human",
    body: "Yeah, no, don't put me down for cardio.",
    source: "Pitch Perfect (2012) — Fat Amy",
    reveal: "That's Fat Amy in Pitch Perfect (2012).",
  },
  {
    id: "genz-6",
    type: "text",
    category: "genz",
    answer: "human",
    body: "I do hope you keep me in mind for any future game nights.",
    source: "Game Night (2018) — Gary",
    reveal: "That's Gary in Game Night (2018).",
  },
  {
    id: "genz-7",
    type: "text",
    category: "genz",
    answer: "human",
    body: '"You guys don\'t even care about school." "No, we just don\'t only care about school."',
    source: "Booksmart (2019) — Molly & Triple A",
    reveal: "That's Molly & Triple A in Booksmart (2019).",
  },
  {
    id: "genz-8",
    type: "text",
    category: "genz",
    answer: "human",
    body: "Maximum effort.",
    source: "Deadpool (2016) — Deadpool",
    reveal: "That's Deadpool in Deadpool (2016).",
  },
  {
    id: "genz-9",
    type: "text",
    category: "genz",
    answer: "human",
    body: "The only thing I do know is that we have to be kind. Please, be kind, especially when we don't know what's going on.",
    source: "Everything Everywhere All at Once (2022) — Waymond Wang",
    reveal: "That's Waymond Wang in Everything Everywhere All at Once (2022).",
  },
  {
    id: "genz-13",
    type: "text",
    category: "genz",
    answer: "bot",
    body: "We're a team now. And being a team means trusting each other, believing in each other, and occasionally stealing a van together.",
    source: "AI-generated",
    tell: "list-of-three",
    reveal: "AI — a warm list of three with a van bolted on the end.",
  },
  {
    id: "genz-15",
    type: "text",
    category: "genz",
    answer: "bot",
    body: "Guys. Guys. Okay, now that I have everyone's full and undivided attention, I would like to formally propose that we absolutely, positively, one hundred percent do not do that again.",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: "AI — five words of emphasis doing one word's job.",
  },
  {
    id: "genz-17",
    type: "text",
    category: "genz",
    answer: "bot",
    body: "And that, my friends, is how you turn a total disaster into a slightly smaller disaster. Teamwork.",
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: "AI — it narrated its own scene and took a bow.",
  },
  {
    id: "genz-18",
    type: "text",
    category: "genz",
    answer: "bot",
    body: "Okay. New plan. Same as the old plan, but this time we run.",
    source: "AI-generated",
    reveal: "Sneaky — short, funny, straight out of a real jam; nothing went wrong on your end.",
    sneaky: true,
  },
  {
    id: "genz-19",
    type: "text",
    category: "genz",
    answer: "bot",
    body: "You said you had a plan. You did not say the plan was a shopping cart.",
    source: "AI-generated",
    reveal:
      "Sneaky — a specific, stupid object is usually the human giveaway; right bet, wrong card.",
    sneaky: true,
  },
  {
    id: "genz-20",
    type: "text",
    category: "genz",
    answer: "bot",
    body: "I'm not scared. My legs are scared. There's a difference and I'd rather not get into it right now.",
    source: "AI-generated",
    reveal: "Sneaky — refusing to explain your own joke is about the most human move there is.",
    sneaky: true,
  },
  {
    id: "alpha-1",
    type: "text",
    category: "alpha",
    answer: "human",
    body: "Rats along his back. When he calls your name, it all fades to black.",
    source: "Encanto (2021) — Camilo, “We Don't Talk About Bruno”",
    reveal: "That's Camilo, “We Don't Talk About Bruno” in Encanto (2021).",
  },
  {
    id: "alpha-2",
    type: "text",
    category: "alpha",
    answer: "human",
    body: "But Aunt Lucy said, “If we're kind and polite, the world will be right.”",
    source: "Paddington 2 (2017) — Paddington",
    reveal: "That's Paddington in Paddington 2 (2017).",
  },
  {
    id: "alpha-3",
    type: "text",
    category: "alpha",
    answer: "human",
    body: "He's so fluffy, I'm gonna die!",
    source: "Despicable Me (2010) — Agnes",
    reveal: "That's Agnes in Despicable Me (2010).",
  },
  {
    id: "alpha-4",
    type: "text",
    category: "alpha",
    answer: "human",
    body: "And I don't mean it metaphorically or rhetorically or poetically or theoretically or in any other fancy way. I'm Death, straight up.",
    source: "Puss in Boots: The Last Wish (2022) — Death",
    reveal: "That's Death in Puss in Boots: The Last Wish (2022).",
  },
  {
    id: "alpha-5",
    type: "text",
    category: "alpha",
    answer: "human",
    body: "If you start singing, I'm gonna throw up.",
    source: "Moana (2016) — Maui",
    reveal: "That's Maui in Moana (2016).",
  },
  {
    id: "alpha-6",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: "“In today's fast-paced forest landscape, snack security is more important than ever,” announced the squirrel from the top of the picnic table. “Which is why I will now be taking that sandwich.”",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal:
      'AI — the "In today\'s fast-paced..." opener, delivered by a sandwich-stealing squirrel.',
  },
  {
    id: "alpha-7",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: "“This isn't just a snowball fight,” said the penguin, adjusting his tiny scarf. “It's a chance to build something bigger than ourselves.”",
    source: "AI-generated",
    tell: "not-just-x",
    reveal: 'AI — the "not just X" upgrade, snowball-fight edition.',
  },
  {
    id: "alpha-8",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: "“Before we delve into who ate the cake,” said the hamster, “let us take a moment to appreciate the rich tapestry of crumbs on this floor. Truly a testament to a family that eats together.”",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: 'AI — hamsters don\'t say "rich tapestry."',
  },
  {
    id: "genx-36",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "We hid the entire pep band in the gym storage closet for forty minutes. They came out the wrong door, still playing, and marched straight into somebody's wedding. Which just goes to show, the plans that fall apart are the ones you keep forever.",
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: "AI — the wedding was the punchline; the fortune cookie came after.",
  },
  {
    id: "movies-49",
    type: "text",
    category: "movies",
    answer: "bot",
    body: '"Reactor\'s at a hundred percent." "What happens after a hundred?" "The manual stops at a hundred. There\'s just a phone number." Funny how the moments that terrify us are the ones that show us who we really are.',
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: "AI — the reactor hit 100 and the script paused to reflect.",
  },
  {
    id: "alpha-11",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: '"Is everybody buckled?" "Yep." "Is the dog buckled?" "The dog is driving." "The dog is WHAT?" Turns out the vacation we needed was never the one printed on the map.',
    source: "AI-generated",
    tell: "tidy-closer",
    reveal: "AI — cover the last sentence with your thumb; nothing is missing.",
  },
  {
    id: "bbq-41",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "Pulled the pork butt off the smoker tonight and I am wholly, thoroughly, and completely satisfied with how it turned out. The flavor was immensely flavorful. Highly recommend this cook to anyone.",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: 'AI — "immensely flavorful" means the flavor was flavorful.',
  },
  {
    id: "disney-25",
    type: "text",
    category: "disney",
    answer: "bot",
    body: "“Do not fret, little one,” said the badger, patting the acorn with one paw. “I am entirely, sincerely, and wholeheartedly certain that everything is going to work out extraordinarily well in the end.”",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: "AI — three ways of sounding certain, zero reasons to be.",
  },
  {
    id: "speech-17",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "Graduates, I am incredibly, tremendously, and unbelievably proud of each and every one of you. What all of you have accomplished here is genuinely, authentically remarkable.",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: "AI — the praise keeps swelling; the graduates never come into focus.",
  },
  {
    id: "movies-50",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "Am I in? Buddy, I am fundamentally, comprehensively, and permanently on board. I have never in my entire life been more on board with a plan than I am with this plan right now.",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: 'AI — that\'s three giant words for "yes."',
  },
  {
    id: "movies-51",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "Captain, this vessel and everyone aboard her are utterly, unequivocally, irreversibly doomed. I recommend we respond with maximum urgency.",
    source: "AI-generated",
    tell: "stacked-intensifiers",
    reveal: 'AI — "maximum urgency" is not an order.',
  },
  {
    id: "bbq-42",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "A backyard cook is not measured in pounds of pork. It is measured in the trust of everyone standing there holding a paper plate.",
    source: "AI-generated",
    tell: "not-just-x",
    reveal: 'AI — another "not measured in X" swap; the pork was measured in pounds.',
  },
  {
    id: "business-25",
    type: "text",
    category: "business",
    answer: "bot",
    body: "Thanks for flagging this! Honestly, this thread was never about the parking spots. It was about who we choose to be when the lot fills up.",
    source: "AI-generated",
    tell: "not-just-x",
    reveal: 'AI — the "this was never about X" move, deployed on parking spots.',
  },
  {
    id: "speech-18",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "The gown you are wearing today is not merely a rental, but the final costume of the person you used to be.",
    source: "AI-generated",
    tell: "not-just-x",
    reveal: 'AI — "not merely X, but Y," performed on a rented gown.',
  },
  {
    id: "genx-37",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "This is bigger than a bowling trophy, Dale. This is about whether anybody in this town still believes in anything.",
    source: "AI-generated",
    tell: "not-just-x",
    reveal:
      "AI — a bowling trophy inflated into a town's whole belief system — it's a trophy, Dale.",
  },
  {
    id: "alpha-12",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: "“What started as a hunt for one missing sock,” the raccoon said quietly, “had become a hunt for who we are as a family.”",
    source: "AI-generated",
    tell: "not-just-x",
    reveal: 'AI — one sock, upgraded to "who we are as a family."',
  },
  {
    id: "bbq-43",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "Hi all, hope everyone is having a wonderful Saturday! So sorry to bother the group, but a very large dog has run off with the entire brisket and is heading toward the creek. Only if anyone happens to be free. No pressure either way!",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: 'AI — "no pressure either way" about a stolen brisket.',
  },
  {
    id: "business-26",
    type: "text",
    category: "business",
    answer: "bot",
    body: "Thank you all so much for your hard work this quarter, and I truly appreciate everyone’s dedication. I did want to gently flag, when you have a moment, that the entire customer database was deleted this morning. Great effort all around!",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: "AI — the database is gone but great effort all around.",
  },
  {
    id: "disney-26",
    type: "text",
    category: "disney",
    answer: "bot",
    body: "“Excuse me, Mister Hawk,” said the rabbit as the shadow closed in, “I hate to be a bother, and your talons really are lovely, but I was rather hoping to keep my afternoon free.”",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: "AI — the rabbit complimented the talons mid-swoop.",
  },
  {
    id: "speech-19",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "I am told that siren means a tornado, and we will absolutely be heading to the basement shortly. Before we do, though, I would be remiss not to thank the faculty, the parents, and the wonderful volunteers who set up all of these chairs.",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: "AI — it thanked the chair volunteers into the tornado.",
  },
  {
    id: "genx-38",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "I don’t mean to be a backseat driver, and you are doing wonderfully, but if it isn’t too much trouble, might we consider losing the eleven police cars? Whenever you get a chance. Truly no rush.",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: 'AI — eleven police cars, "truly no rush."',
  },
  {
    id: "millennial-36",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "Hi team, hope you are all well. Truly no big deal, and I am sure it was an honest mistake, but someone has eaten my labeled lunch three days running. Sending gratitude to whoever it was!",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: "AI — it sent gratitude to the lunch thief.",
  },
  {
    id: "alpha-13",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: "“I recognize that this is a very big feeling,” the dad said calmly while the toddler screamed in aisle nine, “and I want to sincerely thank you for sharing it with the entire store.”",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: "AI — nobody thanks a toddler for screaming.",
  },
  {
    id: "movies-52",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "Bridge, so sorry to bother you during shift change. I hate to be the bearer of bad news, but something enormous has come through the hull and it does not appear to be friendly. Take your time!",
    source: "AI-generated",
    tell: "over-politeness",
    reveal: 'AI — "Take your time!" about the thing coming through the hull.',
  },
  {
    id: "bbq-44",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "Certainly! Here are three excellent wood choices for pork: • Apple — mild and slightly sweet • Cherry — beautiful color • Hickory — bold and traditional. Happy smoking!",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: 'AI — a real cook just names the wood; only a chatbot opens with "Certainly!"',
  },
  {
    id: "business-27",
    type: "text",
    category: "business",
    answer: "bot",
    body: "Hi Dana — great question! Regarding the 3pm: 1) Availability — my calendar is clear. 2) Preparation — I will review the deck beforehand. 3) Follow-up — I will circulate notes after. Let me know if you'd like me to expand on any of these.",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: 'AI — a three-part labeled memo, when "yes" would have covered it.',
  },
  {
    id: "disney-27",
    type: "text",
    category: "disney",
    answer: "bot",
    body: "“There now, little fawn,” said the old owl. “Your feelings are completely valid. **Step 1: Breathe.** **Step 2: Name the fear.** **Step 3: Take one small step.** You've got this!”",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: "AI — the owl left its ** formatting marks on the pep talk.",
  },
  {
    id: "speech-20",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "Before you toss your caps, here are my key takeaways: 1) Be curious. 2) Be kind. 3) Be persistent. In summary, the future belongs to those who show up. Congratulations, graduates!",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: 'AI — "key takeaways" in a cap and gown.',
  },
  {
    id: "genx-39",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "The cops are at the door. Okay — quick breakdown of our options: • Option A: the window • Option B: the laundry chute • Option C: honesty. Each has trade-offs. Thoughts?",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: "AI — Options A, B, and C while the cops are knocking.",
  },
  {
    id: "millennial-37",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "**Summary:** I ate your leftovers. **Context:** I was hungry. **Impact:** Acknowledged. **Proposed remedy:** replacement by Sunday. Would you like me to elaborate on any section?",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: "AI — leftovers, four labeled sections, and an offer to elaborate.",
  },
  {
    id: "alpha-14",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: "“Family meeting!” barked the dog. “Agenda item one: the mailman. Agenda item two: the vacuum. Agenda item three: snacks. I have also prepared a short recap for anyone joining late.”",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: "AI — dogs don't have agenda items.",
  },
  {
    id: "movies-53",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "Hull breach in ninety seconds. Here is the plan: Step 1) Seal deck four. Step 2) Reroute auxiliary power. Step 3) Get everyone off the bridge. Shall I proceed, or would you like me to adjust the sequence?",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: "AI — ninety seconds to live and it asks permission to proceed.",
  },
  {
    id: "speech-21",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "A quick toast, organized into three parts. **Part one: How they met.** **Part two: Why it works.** **Part three: The wish.** Please hold applause until the end of the outline.",
    source: "AI-generated",
    tell: "preformatted-answer",
    reveal: "AI — a toast with an outline is a memo in a tux.",
  },
  {
    id: "bbq-45",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "Q: Brisket has been stuck at 160 for four hours, do I wrap it? A: Let me make sure I have your question right. Your brisket has been stuck at 160 for four hours and you want to know whether to wrap it. Four hours is a meaningful stretch of time.",
    source: "AI-generated",
    tell: "restates-question",
    reveal: "AI — four hours stuck at 160 and it read your question back to you.",
  },
  {
    id: "business-28",
    type: "text",
    category: "business",
    answer: "bot",
    body: "Thanks for flagging this. To restate the question: you're asking whether we will make payroll on Friday. Whether we make payroll on Friday is absolutely the right thing to be focused on, and I want to give it the thoughtful response it deserves.",
    source: "AI-generated",
    tell: "restates-question",
    reveal: "AI — payroll is Friday and the reply restated the question.",
  },
  {
    id: "disney-28",
    type: "text",
    category: "disney",
    answer: "bot",
    body: "“Owl, is the water still rising?” “Is the water still rising. What a thoughtful thing to ask, little one. Few creatures in this wood stop to wonder about the water at all, and here you are, wondering.”",
    source: "AI-generated",
    tell: "restates-question",
    reveal: "AI — the owl praised the question while the water kept rising.",
  },
  {
    id: "speech-22",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "A student stopped me last night and asked, “What do we do now?” What do you do now. I want to stay with that question a moment. It is a question, it is yours, and the fact that you asked it says everything about this class.",
    source: "AI-generated",
    tell: "restates-question",
    reveal:
      "AI — a whole speech spent holding the question up to the light instead of answering it.",
  },
  {
    id: "genx-40",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "“Which wire do I cut?” “Which wire do you cut. Terrific question. Honestly, one of the better ones anyone has asked me in this parking garage, and I have been down here since Tuesday.”",
    source: "AI-generated",
    tell: "restates-question",
    reveal: "AI — the bomb got a compliment instead of a wire.",
  },
  {
    id: "millennial-38",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "“Did you mail the invitations?” “Did I mail the invitations. Wow. Okay. That is exactly the question I would be asking if I were standing where you are standing, and I respect it enormously.”",
    source: "AI-generated",
    tell: "restates-question",
    reveal: "AI — question echoed, asker admired, yes or no never supplied.",
  },
  {
    id: "alpha-15",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: "“Dad, are we lost?” “Are we lost. Buddy, that is a big question, and I think it is one this whole family has earned the right to ask.” The van continued in the wrong direction.",
    source: "AI-generated",
    tell: "restates-question",
    reveal: 'AI — "Are we lost" got repeated, weighed, and honored — never answered.',
  },
  {
    id: "movies-54",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "“How long until the core blows?” “How long until the core blows. Excellent question, Commander, and one that gets right to the heart of what every soul aboard this ship is feeling.”",
    source: "AI-generated",
    tell: "restates-question",
    reveal: 'AI — the core got an "Excellent question" instead of a number.',
  },
  {
    id: "bbq-46",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "What a fantastic question, and you're so right to push back — sorry for any mix-up on my end. Your instinct to run 225 is excellent. And if 275 feels better to you, I think that's a wonderful choice too and I completely agree.",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: "AI — it agreed with 225, then agreed with 275 one sentence later.",
  },
  {
    id: "business-29",
    type: "text",
    category: "business",
    answer: "bot",
    body: "Susan, what a sharp callout — I should have caught that myself. Apologies for the confusion on slide four. I really love where your head is at here, and I'm happy to change the forecast to whatever number feels right to you.",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: "AI — Susan could have said any number and it would have loved that one too.",
  },
  {
    id: "disney-29",
    type: "text",
    category: "disney",
    answer: "bot",
    body: "“Oh, you are SO wise, little one,” chirped the squirrel, bowing low. “And I'm terribly sorry if I upset you. Whatever you think the golden acorn means, that is exactly what it means. What a beautiful mind you have.”",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: "AI — flatter and fold: sidekicks argue, bots bow.",
  },
  {
    id: "speech-23",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "Before I begin, let me just say what an incredible audience you are. And if anything I say tonight lands wrong, I apologize in advance, and you are almost certainly right. Honestly, any one of you could give this speech better than me.",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: "AI — it apologized for the speech before giving it.",
  },
  {
    id: "genx-41",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "“You call that a parking job?” “Wow, okay, that is a really fair observation and I'm sorry. You clearly know a lot about parking, way more than I do. I would genuinely love your notes.”",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: "AI — the instant cave: insulted his parking, got a thank-you note.",
  },
  {
    id: "millennial-39",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "“You are hands down the smartest person in this office, and I say that with total respect. Also, I'm sorry. I don't know what for yet, but I can feel that I'm sorry, and you were right about everything.”",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: "AI — the classic bot apology: sorry for nothing, right about everything.",
  },
  {
    id: "alpha-16",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: "“I'm sorry, I'm sorry!” beeped the little robot vacuum. “You're the best kid in this whole house and your plan is so much better than mine. Please don't be mad. We'll do it your way, even the part with the lava.”",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: "AI — it approved the lava plan just to avoid an argument.",
  },
  {
    id: "movies-55",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "“Captain, the reactor is past critical.” “Cut the coolant.” “Excellent instinct, Captain, and I'm sorry for questioning you. Cutting coolant now. What a thoughtful decision to make under this much pressure.”",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: "AI — the reactor is past critical and the computer is complimenting the order.",
  },
  {
    id: "business-30",
    type: "text",
    category: "business",
    answer: "bot",
    body: "“My package never arrived.” “You are so right to reach out, and what a clearly written message. I'm very sorry for the trouble. That said, if you feel the package did arrive, I fully support that as well. Thank you for being such a valued partner.”",
    source: "AI-generated",
    tell: "sycophancy",
    reveal: "AI — sorry your package is missing, and also maybe it isn't.",
  },
  {
    id: "business-31",
    type: "text",
    category: "business",
    answer: "bot",
    body: "Appreciate the patience here. The launch moved for three reasons: bandwidth, timing, and a real commitment to quality. Happy to walk through any of it live.",
    source: "AI-generated",
    tell: "list-of-three",
    reveal: "AI — three reasons, none of them a reason.",
  },
  {
    id: "disney-30",
    type: "text",
    category: "disney",
    answer: "bot",
    body: "“An acorn only needs three things to become an oak,” said the old badger, patting the sapling. “Good soil, steady rain, and the courage to believe in itself.”",
    source: "AI-generated",
    tell: "list-of-three",
    reveal: "AI — soil, rain, and... courage; the real third one was sunlight.",
  },
  {
    id: "movies-56",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "The reactor breach gives us four minutes. Getting off this ship will take three things: steady hands, a clear channel, and faith in each other. Move.",
    source: "AI-generated",
    tell: "list-of-three",
    reveal: "AI — four minutes left and he's itemizing.",
  },
  {
    id: "bbq-47",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "In an era of ever-shifting food trends, it is worth taking a moment to reflect on what really matters out here at the grill. Somebody has walked off with my tongs again.",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal: "AI — a paragraph about food trends before asking for the tongs back.",
  },
  {
    id: "business-32",
    type: "text",
    category: "business",
    answer: "bot",
    body: "As we navigate an increasingly complex scheduling landscape, it is important to step back and think about how we align on shared availability. Yes, 2:00 works for me.",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal: "AI — cross out the first sentence and nothing is lost.",
  },
  {
    id: "disney-31",
    type: "text",
    category: "disney",
    answer: "bot",
    body: "“In a world where the pond changes a little more with every passing season,” the duck said gravely from the top of the flat rock, “one thing has stayed the same. That is my rock, and you are standing on it.”",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal: "AI — the state of the pond has nothing to do with the rock.",
  },
  {
    id: "speech-24",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "In today's ever-evolving campus environment, few moments carry the weight of the one we share this afternoon. Before we begin, the owner of the silver sedan blocking the loading dock needs to move it now.",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal: "AI — the sedan was urgent; the opener was not.",
  },
  {
    id: "millennial-40",
    type: "text",
    category: "millennial",
    answer: "bot",
    body: "At a moment when the modern wedding reception asks more of us than ever, we owe each other some honesty. The open bar closes in nine minutes and Dave is already crying in the parking lot.",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal: "AI — that opener works for weddings, dentistry, or supply chains.",
  },
  {
    id: "movies-57",
    type: "text",
    category: "movies",
    answer: "bot",
    body: "Amid the ever-accelerating pace of interstellar conflict, it is worth pausing to consider the bigger picture. Also, the reactor breaches in forty seconds and somebody welded the door behind you.",
    source: "AI-generated",
    tell: "in-todays-world",
    reveal: "AI — it spent one of your forty seconds on the bigger picture.",
  },
  {
    id: "bbq-48",
    type: "text",
    category: "bbq",
    answer: "bot",
    body: "Fired up the offset at 4 a.m. to elevate a humble pork shoulder into something the whole cul-de-sac will remember.",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: 'AI — you cook a pork shoulder; you don\'t "elevate" it.',
  },
  {
    id: "business-33",
    type: "text",
    category: "business",
    answer: "bot",
    body: "Thanks for flagging! Happy to unlock some time Thursday to align on the potluck sign-up sheet.",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: "AI — no human being has ever unlocked a Thursday.",
  },
  {
    id: "disney-32",
    type: "text",
    category: "disney",
    answer: "bot",
    body: "“The river has risen again,” said the old raccoon, resting a paw on the boy's shoulder. “Together, we must navigate the challenges ahead.”",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: 'AI — raccoons cross rivers; chatbots "navigate the challenges ahead."',
  },
  {
    id: "speech-25",
    type: "text",
    category: "speech",
    answer: "bot",
    body: "Graduates, beyond these doors awaits a myriad of opportunities, each one ready for you to seize it.",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: 'AI — "myriad," said no one out loud, ever.',
  },
  {
    id: "genx-42",
    type: "text",
    category: "genx",
    answer: "bot",
    body: "Trust me, man. Sneaking into the faculty lounge is the pivotal moment of our entire senior year.",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: 'AI — "pivotal" is deck-speak, not senior-year speak.',
  },
  {
    id: "alpha-17",
    type: "text",
    category: "alpha",
    answer: "bot",
    body: "The eight-year-old folded her arms on the minivan seat. “All I'm asking,” she said, “is that this family foster a more open dialogue about bedtime.”",
    source: "AI-generated",
    tell: "machine-vocab",
    reveal: 'AI — third graders don\'t "foster" anything.',
  },
];

export const BY_ID: Record<string, FullQuestion> = Object.fromEntries(
  FULL_QUESTIONS.map((q) => [q.id, q]),
);
